package cpp

import (
	"fmt"
	"strings"

	"github.com/rdeusser/cleave/internal/codegen"
	"github.com/rdeusser/cleave/internal/ir"
)

type Generator struct{}

func (g *Generator) Generate(pkg *ir.Package) ([]codegen.OutputFile, error) {
	h := &writer{pkg: pkg}
	h.generateHeader()

	s := &writer{pkg: pkg}
	s.generateSource()

	return []codegen.OutputFile{
		{Name: pkg.Name + ".h", Content: []byte(h.sb.String())},
		{Name: pkg.Name + ".cpp", Content: []byte(s.sb.String())},
	}, nil
}

type writer struct {
	sb  strings.Builder
	pkg *ir.Package
}

func (w *writer) generateHeader() {
	w.sb.WriteString("// Generated by cleave. Do not edit.\n")
	w.sb.WriteString("#pragma once\n\n")
	w.sb.WriteString("#include <cstdint>\n")
	w.sb.WriteString("#include <cstring>\n")
	w.sb.WriteString("#include <string>\n")
	w.sb.WriteString("#include <vector>\n")
	w.sb.WriteString("#include <stdexcept>\n")
	if w.hasConditionalFields() {
		w.sb.WriteString("#include <optional>\n")
	}
	if w.hasMatchFields() {
		w.sb.WriteString("#include <variant>\n")
	}
	if w.hasCrossRefFields() {
		w.sb.WriteString("#include <unordered_map>\n")
	}
	w.sb.WriteString("\n")

	fmt.Fprintf(&w.sb, "namespace %s {\n", w.pkg.Name)

	for _, e := range w.pkg.Enums {
		w.sb.WriteString("\n")
		w.writeEnumHeader(e)
	}

	for _, s := range w.pkg.Structs {
		w.sb.WriteString("\n")
		w.writeStructHeader(s)
	}

	fmt.Fprintf(&w.sb, "\n} // namespace %s\n", w.pkg.Name)
}

func (w *writer) generateSource() {
	usedSizes := w.collectEndianSizes()

	w.sb.WriteString("// Generated by cleave. Do not edit.\n")
	fmt.Fprintf(&w.sb, "#include \"%s.h\"\n\n", w.pkg.Name)

	fmt.Fprintf(&w.sb, "namespace %s {\n", w.pkg.Name)

	if len(usedSizes) > 0 {
		w.sb.WriteString("\nnamespace {\n")
		for _, size := range []int{2, 4, 8} {
			if usedSizes[size] {
				w.writeEndianHelper(size)
			}
		}
		w.sb.WriteString("\n} // namespace\n")
	}

	for _, s := range w.pkg.Structs {
		w.sb.WriteString("\n")
		w.writeStructSource(s)
	}

	fmt.Fprintf(&w.sb, "\n} // namespace %s\n", w.pkg.Name)
}

func (w *writer) writeEnumHeader(e *ir.Enum) {
	cppType := cppPrimitiveType(e.BackingType)
	fmt.Fprintf(&w.sb, "enum class %s : %s {\n", e.Name, cppType)
	for _, v := range e.Variants {
		fmt.Fprintf(&w.sb, "    %s = %d,\n", v.Name, v.Value)
	}
	w.sb.WriteString("};\n")
}

func (w *writer) writeStructHeader(s *ir.Struct) {
	fmt.Fprintf(&w.sb, "struct %s {\n", s.Name)
	for _, f := range s.Fields {
		var typeName string
		if f.Type.Kind == ir.KindMatch {
			typeName = w.variantType(f.Match)
		} else if f.Type.Kind == ir.KindPrimitive && f.Type.Array.Kind == ir.FixedSize &&
			(f.Type.Primitive == ir.Bytes || f.Type.Primitive == ir.String) &&
			f.Encoding == "" {
			if f.Condition != nil {
				fmt.Fprintf(&w.sb, "    std::optional<std::vector<uint8_t>> %s;\n", f.Name)
			} else {
				fmt.Fprintf(&w.sb, "    uint8_t %s[%d];\n", f.Name, f.Type.Array.FixedSize)
			}
			continue
		} else {
			typeName = cppFieldType(f)
		}

		if f.Condition != nil {
			fmt.Fprintf(&w.sb, "    std::optional<%s> %s;\n", typeName, f.Name)
		} else {
			fmt.Fprintf(&w.sb, "    %s %s;\n", typeName, f.Name)
		}
	}
	w.sb.WriteString("\n")
	fmt.Fprintf(&w.sb, "    static %s parse(const uint8_t* buf, size_t len, size_t& offset);\n", s.Name)
	w.sb.WriteString("    std::string to_json() const;\n")
	w.sb.WriteString("    std::vector<uint8_t> to_bytes() const;\n")
	if structHasCrossRefs(s) {
		w.sb.WriteString("    static std::unordered_map<std::string, std::string> refs();\n")
	}
	w.sb.WriteString("};\n")
}

func (w *writer) writeStructSource(s *ir.Struct) {
	// Parse method.
	fmt.Fprintf(&w.sb, "%s %s::parse(const uint8_t* buf, size_t len, size_t& offset) {\n", s.Name, s.Name)
	fmt.Fprintf(&w.sb, "    %s result;\n", s.Name)

	for _, f := range s.Fields {
		endian := f.EffectiveEndian(s.Options.Endian)
		isBig := endian == ir.BigEndian

		if f.Condition != nil {
			fmt.Fprintf(&w.sb, "    if (%s) {\n", emitCppExpr(f.Condition, ""))

			var readBuf strings.Builder
			orig := w.sb
			w.sb = readBuf

			switch f.Type.Kind {
			case ir.KindMatch:
				w.writeMatchParse(f, s, isBig)
			case ir.KindStruct:
				switch f.Type.Array.Kind {
				case ir.RestArray:
					fmt.Fprintf(&w.sb, "    while (offset < len) {\n")
					fmt.Fprintf(&w.sb, "        result.%s.push_back(%s::parse(buf, len, offset));\n", f.Name, f.Type.Ref)
					fmt.Fprintf(&w.sb, "    }\n")
				case ir.CountRef:
					fmt.Fprintf(&w.sb, "    for (size_t i = 0; i < result.%s; ++i) {\n", f.Type.Array.CountRef)
					fmt.Fprintf(&w.sb, "        result.%s.push_back(%s::parse(buf, len, offset));\n", f.Name, f.Type.Ref)
					fmt.Fprintf(&w.sb, "    }\n")
				default:
					fmt.Fprintf(&w.sb, "    result.%s = %s::parse(buf, len, offset);\n", f.Name, f.Type.Ref)
				}
			case ir.KindEnum:
				e := w.lookupEnum(f.Type.Ref)
				size := e.BackingType.Size()
				cppBacking := cppPrimitiveType(e.BackingType)
				w.writeReadPrimitive(f.Name, cppBacking, size, isBig, false)
				fmt.Fprintf(&w.sb, "    result.%s = static_cast<%s>(%s);\n", f.Name, f.Type.Ref, f.Name)
			case ir.KindPrimitive:
				w.writeCppPrimitiveRead(f, isBig)
			}

			readCode := w.sb.String()
			w.sb = orig

			for _, line := range strings.Split(readCode, "\n") {
				if line == "" {
					continue
				}
				fmt.Fprintf(&w.sb, "    %s\n", line)
			}

			for _, v := range f.Validations {
				fmt.Fprintf(&w.sb, "        if (!(%s)) {\n", emitCppExpr(v.Expression, "result."+f.Name))
				fmt.Fprintf(&w.sb, "            throw std::runtime_error(%q);\n", v.Message)
				fmt.Fprintf(&w.sb, "        }\n")
			}

			w.sb.WriteString("    }\n")
		} else {
			switch f.Type.Kind {
			case ir.KindMatch:
				w.writeMatchParse(f, s, isBig)

			case ir.KindStruct:
				switch f.Type.Array.Kind {
				case ir.RestArray:
					fmt.Fprintf(&w.sb, "    while (offset < len) {\n")
					fmt.Fprintf(&w.sb, "        result.%s.push_back(%s::parse(buf, len, offset));\n", f.Name, f.Type.Ref)
					fmt.Fprintf(&w.sb, "    }\n")
				case ir.CountRef:
					fmt.Fprintf(&w.sb, "    for (size_t i = 0; i < result.%s; ++i) {\n", f.Type.Array.CountRef)
					fmt.Fprintf(&w.sb, "        result.%s.push_back(%s::parse(buf, len, offset));\n", f.Name, f.Type.Ref)
					fmt.Fprintf(&w.sb, "    }\n")
				default:
					fmt.Fprintf(&w.sb, "    result.%s = %s::parse(buf, len, offset);\n", f.Name, f.Type.Ref)
				}

			case ir.KindEnum:
				e := w.lookupEnum(f.Type.Ref)
				size := e.BackingType.Size()
				cppBacking := cppPrimitiveType(e.BackingType)
				w.writeReadPrimitive(f.Name, cppBacking, size, isBig, false)
				fmt.Fprintf(&w.sb, "    result.%s = static_cast<%s>(%s);\n", f.Name, f.Type.Ref, f.Name)

			case ir.KindPrimitive:
				w.writeCppPrimitiveRead(f, isBig)
			}

			for _, v := range f.Validations {
				fmt.Fprintf(&w.sb, "    if (!(%s)) {\n", emitCppExpr(v.Expression, "result."+f.Name))
				fmt.Fprintf(&w.sb, "        throw std::runtime_error(%q);\n", v.Message)
				fmt.Fprintf(&w.sb, "    }\n")
			}
		}
	}

	w.sb.WriteString("    return result;\n")
	w.sb.WriteString("}\n\n")

	// JSON serialization method.
	fmt.Fprintf(&w.sb, "std::string %s::to_json() const {\n", s.Name)
	w.sb.WriteString("    std::string s = \"{\";\n")

	for i, f := range s.Fields {
		if i > 0 {
			w.sb.WriteString("    s += \",\";\n")
		}
		fmt.Fprintf(&w.sb, "    s += \"\\\"%s\\\":\";\n", f.Name)

		accessName := f.Name
		if f.Condition != nil {
			fmt.Fprintf(&w.sb, "    if (%s.has_value()) {\n", f.Name)
			accessName = f.Name + ".value()"
		}

		indent := "    "
		if f.Condition != nil {
			indent = "        "
		}

		switch {
		case f.Type.Kind == ir.KindMatch:
			w.writeMatchJSON(f)

		case f.Type.Kind == ir.KindStruct:
			if f.Type.Array.Kind == ir.RestArray || f.Type.Array.Kind == ir.CountRef {
				fmt.Fprintf(&w.sb, "%ss += \"[\";\n", indent)
				fmt.Fprintf(&w.sb, "%sfor (size_t i = 0; i < %s.size(); ++i) {\n", indent, accessName)
				fmt.Fprintf(&w.sb, "%s    if (i > 0) s += \",\";\n", indent)
				fmt.Fprintf(&w.sb, "%s    s += %s[i].to_json();\n", indent, accessName)
				fmt.Fprintf(&w.sb, "%s}\n", indent)
				fmt.Fprintf(&w.sb, "%ss += \"]\";\n", indent)
			} else {
				fmt.Fprintf(&w.sb, "%ss += %s.to_json();\n", indent, accessName)
			}

		case f.Type.Kind == ir.KindEnum:
			fmt.Fprintf(&w.sb, "%ss += std::to_string(static_cast<int>(%s));\n", indent, accessName)

		case (f.Type.Primitive == ir.Bytes || f.Type.Primitive == ir.String) && f.Type.Array.Kind == ir.FixedTerminator:
			fmt.Fprintf(&w.sb, "%ss += \"\\\"\" + %s + \"\\\"\";\n", indent, accessName)

		case (f.Type.Primitive == ir.Bytes || f.Type.Primitive == ir.String) && f.Encoding != "":
			fmt.Fprintf(&w.sb, "%ss += \"\\\"\" + %s + \"\\\"\";\n", indent, accessName)

		case f.Type.Primitive == ir.Bytes || f.Type.Primitive == ir.String:
			if f.Condition != nil {
				w.writeBytesJSONWithIndent(f, accessName, indent)
			} else {
				w.writeBytesJSON(f)
			}

		case f.Type.Primitive == ir.F32 || f.Type.Primitive == ir.F64:
			if f.Type.Array.Kind != ir.NotArray {
				fmt.Fprintf(&w.sb, "%ss += \"[\";\n", indent)
				fmt.Fprintf(&w.sb, "%sfor (size_t i = 0; i < %s.size(); ++i) {\n", indent, accessName)
				fmt.Fprintf(&w.sb, "%s    if (i > 0) s += \",\";\n", indent)
				fmt.Fprintf(&w.sb, "%s    s += std::to_string(%s[i]);\n", indent, accessName)
				fmt.Fprintf(&w.sb, "%s}\n", indent)
				fmt.Fprintf(&w.sb, "%ss += \"]\";\n", indent)
			} else {
				fmt.Fprintf(&w.sb, "%ss += std::to_string(%s);\n", indent, accessName)
			}

		default:
			if f.Type.Array.Kind != ir.NotArray {
				fmt.Fprintf(&w.sb, "%ss += \"[\";\n", indent)
				fmt.Fprintf(&w.sb, "%sfor (size_t i = 0; i < %s.size(); ++i) {\n", indent, accessName)
				fmt.Fprintf(&w.sb, "%s    if (i > 0) s += \",\";\n", indent)
				fmt.Fprintf(&w.sb, "%s    s += std::to_string(%s[i]);\n", indent, accessName)
				fmt.Fprintf(&w.sb, "%s}\n", indent)
				fmt.Fprintf(&w.sb, "%ss += \"]\";\n", indent)
			} else {
				fmt.Fprintf(&w.sb, "%ss += std::to_string(%s);\n", indent, accessName)
			}
		}

		if f.Condition != nil {
			w.sb.WriteString("    } else {\n")
			w.sb.WriteString("        s += \"null\";\n")
			w.sb.WriteString("    }\n")
		}
	}

	w.sb.WriteString("    s += \"}\";\n")
	w.sb.WriteString("    return s;\n")
	w.sb.WriteString("}\n\n")

	// Binary serialization method.
	w.writeToBytesSource(s)

	// Cross-reference metadata method.
	if structHasCrossRefs(s) {
		fmt.Fprintf(&w.sb, "\nstd::unordered_map<std::string, std::string> %s::refs() {\n", s.Name)
		fmt.Fprintf(&w.sb, "    return {\n")
		for _, f := range s.Fields {
			if f.CrossRef != "" {
				fmt.Fprintf(&w.sb, "        {%q, %q},\n", f.Name, f.CrossRef)
			}
		}
		fmt.Fprintf(&w.sb, "    };\n")
		fmt.Fprintf(&w.sb, "}\n")
	}
}

func (w *writer) hasConditionalFields() bool {
	for _, s := range w.pkg.Structs {
		for _, f := range s.Fields {
			if f.Condition != nil {
				return true
			}
		}
	}
	return false
}

func (w *writer) hasMatchFields() bool {
	for _, s := range w.pkg.Structs {
		for _, f := range s.Fields {
			if f.Type.Kind == ir.KindMatch {
				return true
			}
		}
	}
	return false
}

func (w *writer) hasCrossRefFields() bool {
	for _, s := range w.pkg.Structs {
		for _, f := range s.Fields {
			if f.CrossRef != "" {
				return true
			}
		}
	}
	return false
}

func (w *writer) variantType(m *ir.MatchSpec) string {
	seen := make(map[string]bool)
	var types []string
	for _, c := range m.Cases {
		t := cppTypeForFieldType(&c.Type)
		if !seen[t] {
			seen[t] = true
			types = append(types, t)
		}
	}
	if m.Default != nil {
		t := cppTypeForFieldType(m.Default)
		if !seen[t] {
			seen[t] = true
			types = append(types, t)
		}
	}
	return fmt.Sprintf("std::variant<%s>", strings.Join(types, ", "))
}

func (w *writer) variantIdx(m *ir.MatchSpec, ft *ir.FieldType) int {
	target := cppTypeForFieldType(ft)
	seen := make(map[string]int)
	idx := 0
	for _, c := range m.Cases {
		t := cppTypeForFieldType(&c.Type)
		if _, exists := seen[t]; !exists {
			seen[t] = idx
			idx++
		}
	}
	if m.Default != nil {
		t := cppTypeForFieldType(m.Default)
		if _, exists := seen[t]; !exists {
			seen[t] = idx
		}
	}
	return seen[target]
}

func (w *writer) writeMatchParse(f *ir.Field, s *ir.Struct, isBig bool) {
	m := f.Match
	for i, c := range m.Cases {
		if i == 0 {
			fmt.Fprintf(&w.sb, "    if (result.%s == %d) {\n", m.TagField, c.Value)
		} else {
			fmt.Fprintf(&w.sb, "    } else if (result.%s == %d) {\n", m.TagField, c.Value)
		}
		w.writeVariantCaseParse(f.Name, &c.Type, w.variantIdx(m, &c.Type), isBig)
	}

	if m.Default != nil {
		w.sb.WriteString("    } else {\n")
		w.writeVariantCaseParse(f.Name, m.Default, w.variantIdx(m, m.Default), isBig)
	} else {
		w.sb.WriteString("    } else {\n")
		fmt.Fprintf(&w.sb, "        throw std::runtime_error(\"unknown tag value for %s.%s\");\n", s.Name, f.Name)
	}
	w.sb.WriteString("    }\n")
}

func (w *writer) writeVariantCaseParse(fieldName string, ft *ir.FieldType, variantIdx int, isBig bool) {
	switch ft.Kind {
	case ir.KindPrimitive:
		if ft.Primitive == ir.Bytes || ft.Primitive == ir.String {
			if ft.Array.Kind == ir.FixedSize {
				fmt.Fprintf(&w.sb, "        if (offset + %d > len) throw std::runtime_error(\"buffer overflow\");\n", ft.Array.FixedSize)
				fmt.Fprintf(&w.sb, "        auto& _bytes = result.%s.emplace<%d>();\n", fieldName, variantIdx)
				fmt.Fprintf(&w.sb, "        _bytes.assign(buf + offset, buf + offset + %d);\n", ft.Array.FixedSize)
				fmt.Fprintf(&w.sb, "        offset += %d;\n", ft.Array.FixedSize)
			}
		} else {
			cppType := cppPrimitiveType(ft.Primitive)
			size := ft.Primitive.Size()
			fmt.Fprintf(&w.sb, "        auto& _val = result.%s.emplace<%d>();\n", fieldName, variantIdx)
			if size == 1 {
				fmt.Fprintf(&w.sb, "        if (offset + 1 > len) throw std::runtime_error(\"buffer overflow\");\n")
				fmt.Fprintf(&w.sb, "        _val = static_cast<%s>(buf[offset]);\n", cppType)
				fmt.Fprintf(&w.sb, "        offset += 1;\n")
			} else {
				fmt.Fprintf(&w.sb, "        if (offset + %d > len) throw std::runtime_error(\"buffer overflow\");\n", size)
				fmt.Fprintf(&w.sb, "        std::memcpy(&_val, buf + offset, %d);\n", size)
				if isBig {
					fmt.Fprintf(&w.sb, "        _val = swap%d(_val);\n", size*8)
				}
				fmt.Fprintf(&w.sb, "        offset += %d;\n", size)
			}
		}
	case ir.KindEnum:
		e := w.lookupEnum(ft.Ref)
		cppBacking := cppPrimitiveType(e.BackingType)
		size := e.BackingType.Size()
		fmt.Fprintf(&w.sb, "        %s _tag_val;\n", cppBacking)
		if size == 1 {
			fmt.Fprintf(&w.sb, "        if (offset + 1 > len) throw std::runtime_error(\"buffer overflow\");\n")
			fmt.Fprintf(&w.sb, "        _tag_val = static_cast<%s>(buf[offset]);\n", cppBacking)
			fmt.Fprintf(&w.sb, "        offset += 1;\n")
		} else {
			fmt.Fprintf(&w.sb, "        if (offset + %d > len) throw std::runtime_error(\"buffer overflow\");\n", size)
			fmt.Fprintf(&w.sb, "        std::memcpy(&_tag_val, buf + offset, %d);\n", size)
			if isBig {
				fmt.Fprintf(&w.sb, "        _tag_val = swap%d(_tag_val);\n", size*8)
			}
			fmt.Fprintf(&w.sb, "        offset += %d;\n", size)
		}
		fmt.Fprintf(&w.sb, "        result.%s.emplace<%d>(static_cast<%s>(_tag_val));\n", fieldName, variantIdx, ft.Ref)
	case ir.KindStruct:
		fmt.Fprintf(&w.sb, "        result.%s.emplace<%d>(%s::parse(buf, len, offset));\n", fieldName, variantIdx, ft.Ref)
	}
}

func (w *writer) writeMatchJSON(f *ir.Field) {
	m := f.Match

	for i, c := range m.Cases {
		idx := w.variantIdx(m, &c.Type)
		if i == 0 {
			fmt.Fprintf(&w.sb, "    if (%s.index() == %d) {\n", f.Name, idx)
		} else {
			fmt.Fprintf(&w.sb, "    } else if (%s.index() == %d) {\n", f.Name, idx)
		}
		w.writeVariantCaseJSON(f.Name, &c.Type, idx)
	}

	if m.Default != nil {
		idx := w.variantIdx(m, m.Default)
		fmt.Fprintf(&w.sb, "    } else if (%s.index() == %d) {\n", f.Name, idx)
		w.writeVariantCaseJSON(f.Name, m.Default, idx)
	}
	w.sb.WriteString("    }\n")
}

func (w *writer) writeVariantCaseJSON(fieldName string, ft *ir.FieldType, idx int) {
	switch ft.Kind {
	case ir.KindPrimitive:
		if ft.Primitive == ir.Bytes || ft.Primitive == ir.String {
			fmt.Fprintf(&w.sb, "        auto& _v = std::get<%d>(%s);\n", idx, fieldName)
			w.sb.WriteString("        s += \"[\";\n")
			w.sb.WriteString("        for (size_t i = 0; i < _v.size(); ++i) {\n")
			w.sb.WriteString("            if (i > 0) s += \",\";\n")
			w.sb.WriteString("            s += std::to_string(_v[i]);\n")
			w.sb.WriteString("        }\n")
			w.sb.WriteString("        s += \"]\";\n")
		} else {
			fmt.Fprintf(&w.sb, "        s += std::to_string(std::get<%d>(%s));\n", idx, fieldName)
		}
	case ir.KindEnum:
		fmt.Fprintf(&w.sb, "        s += std::to_string(static_cast<int>(std::get<%d>(%s)));\n", idx, fieldName)
	case ir.KindStruct:
		fmt.Fprintf(&w.sb, "        s += std::get<%d>(%s).to_json();\n", idx, fieldName)
	}
}

func (w *writer) writeCppPrimitiveRead(f *ir.Field, isBig bool) {
	prim := f.Type.Primitive
	cppType := cppPrimitiveType(prim)

	switch f.Type.Array.Kind {
	case ir.NotArray:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "    // bare bytes/string with no length\n")
		} else {
			size := prim.Size()
			w.writeReadPrimitive(fmt.Sprintf("result.%s", f.Name), cppType, size, isBig, true)
		}

	case ir.FixedSize:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "    if (offset + %d > len) throw std::runtime_error(\"buffer overflow\");\n", f.Type.Array.FixedSize)
				fmt.Fprintf(&w.sb, "    result.%s.assign(reinterpret_cast<const char*>(buf + offset), %d);\n", f.Name, f.Type.Array.FixedSize)
				fmt.Fprintf(&w.sb, "    offset += %d;\n", f.Type.Array.FixedSize)
				fmt.Fprintf(&w.sb, "    // encoding: %s\n", f.Encoding)
			} else {
				fmt.Fprintf(&w.sb, "    if (offset + %d > len) throw std::runtime_error(\"buffer overflow\");\n", f.Type.Array.FixedSize)
				fmt.Fprintf(&w.sb, "    std::memcpy(result.%s, buf + offset, %d);\n", f.Name, f.Type.Array.FixedSize)
				fmt.Fprintf(&w.sb, "    offset += %d;\n", f.Type.Array.FixedSize)
			}
		} else {
			size := prim.Size()
			fmt.Fprintf(&w.sb, "    for (int i = 0; i < %d; ++i) {\n", f.Type.Array.FixedSize)
			fmt.Fprintf(&w.sb, "        %s val;\n", cppType)
			w.writeReadPrimitiveInner("val", cppType, size, isBig)
			fmt.Fprintf(&w.sb, "        result.%s.push_back(val);\n", f.Name)
			w.sb.WriteString("    }\n")
		}

	case ir.LengthRef:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "    if (offset + result.%s > len) throw std::runtime_error(\"buffer overflow\");\n", f.Type.Array.LengthRef)
				fmt.Fprintf(&w.sb, "    result.%s.assign(reinterpret_cast<const char*>(buf + offset), result.%s);\n", f.Name, f.Type.Array.LengthRef)
				fmt.Fprintf(&w.sb, "    offset += result.%s;\n", f.Type.Array.LengthRef)
				fmt.Fprintf(&w.sb, "    // encoding: %s\n", f.Encoding)
			} else {
				fmt.Fprintf(&w.sb, "    if (offset + result.%s > len) throw std::runtime_error(\"buffer overflow\");\n", f.Type.Array.LengthRef)
				fmt.Fprintf(&w.sb, "    result.%s.assign(buf + offset, buf + offset + result.%s);\n", f.Name, f.Type.Array.LengthRef)
				fmt.Fprintf(&w.sb, "    offset += result.%s;\n", f.Type.Array.LengthRef)
			}
		} else {
			size := prim.Size()
			fmt.Fprintf(&w.sb, "    for (size_t i = 0; i < result.%s; ++i) {\n", f.Type.Array.LengthRef)
			fmt.Fprintf(&w.sb, "        %s val;\n", cppType)
			w.writeReadPrimitiveInner("val", cppType, size, isBig)
			fmt.Fprintf(&w.sb, "        result.%s.push_back(val);\n", f.Name)
			w.sb.WriteString("    }\n")
		}

	case ir.RestArray:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "    if (offset < len) {\n")
			fmt.Fprintf(&w.sb, "        result.%s.assign(buf + offset, buf + len);\n", f.Name)
			fmt.Fprintf(&w.sb, "        offset = len;\n")
			fmt.Fprintf(&w.sb, "    }\n")
		} else {
			size := prim.Size()
			fmt.Fprintf(&w.sb, "    while (offset + %d <= len) {\n", size)
			fmt.Fprintf(&w.sb, "        %s val;\n", cppType)
			w.writeReadPrimitiveInner("val", cppType, size, isBig)
			fmt.Fprintf(&w.sb, "        result.%s.push_back(val);\n", f.Name)
			w.sb.WriteString("    }\n")
		}

	case ir.Terminator:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "    while (offset < len && buf[offset] != %d) {\n", f.Type.Array.Sentinel)
				fmt.Fprintf(&w.sb, "        result.%s.push_back(static_cast<char>(buf[offset++]));\n", f.Name)
				w.sb.WriteString("    }\n")
				w.sb.WriteString("    if (offset < len) ++offset; // skip sentinel\n")
				fmt.Fprintf(&w.sb, "    // encoding: %s\n", f.Encoding)
			} else {
				fmt.Fprintf(&w.sb, "    while (offset < len && buf[offset] != %d) {\n", f.Type.Array.Sentinel)
				fmt.Fprintf(&w.sb, "        result.%s.push_back(buf[offset++]);\n", f.Name)
				w.sb.WriteString("    }\n")
				w.sb.WriteString("    if (offset < len) ++offset; // skip sentinel\n")
			}
		} else {
			size := prim.Size()
			fmt.Fprintf(&w.sb, "    while (offset + %d <= len) {\n", size)
			fmt.Fprintf(&w.sb, "        %s val;\n", cppType)
			w.writeReadPrimitiveInner("val", cppType, size, isBig)
			fmt.Fprintf(&w.sb, "        if (val == %d) break;\n", f.Type.Array.Sentinel)
			fmt.Fprintf(&w.sb, "        result.%s.push_back(val);\n", f.Name)
			w.sb.WriteString("    }\n")
		}

	case ir.FixedTerminator:
		fmt.Fprintf(&w.sb, "    if (offset + %d > len) throw std::runtime_error(\"buffer overflow\");\n", f.Type.Array.FixedSize)
		fmt.Fprintf(&w.sb, "    {\n")
		fmt.Fprintf(&w.sb, "        size_t _n = strnlen(reinterpret_cast<const char*>(buf + offset), %d);\n", f.Type.Array.FixedSize)
		fmt.Fprintf(&w.sb, "        result.%s.assign(reinterpret_cast<const char*>(buf + offset), _n);\n", f.Name)
		fmt.Fprintf(&w.sb, "        offset += %d;\n", f.Type.Array.FixedSize)
		fmt.Fprintf(&w.sb, "    }\n")
		if f.Encoding != "" {
			fmt.Fprintf(&w.sb, "    // encoding: %s\n", f.Encoding)
		}
	}
}

func (w *writer) writeToBytesSource(s *ir.Struct) {
	lengthSources, countSources := buildAutoComputeMap(s)

	fmt.Fprintf(&w.sb, "std::vector<uint8_t> %s::to_bytes() const {\n", s.Name)
	fmt.Fprintf(&w.sb, "    std::vector<uint8_t> _buf;\n")

	for _, f := range s.Fields {
		endian := f.EffectiveEndian(s.Options.Endian)
		isBig := endian == ir.BigEndian

		if f.Condition != nil {
			fmt.Fprintf(&w.sb, "    if (%s.has_value()) {\n", f.Name)

			var writeBuf strings.Builder
			orig := w.sb
			w.sb = writeBuf

			switch f.Type.Kind {
			case ir.KindMatch:
				w.writeMatchWrite(f, s, isBig)
			case ir.KindStruct:
				switch f.Type.Array.Kind {
				case ir.RestArray, ir.CountRef:
					fmt.Fprintf(&w.sb, "    for (const auto& _item : %s.value()) {\n", f.Name)
					fmt.Fprintf(&w.sb, "        auto _tmp = _item.to_bytes();\n")
					fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());\n")
					fmt.Fprintf(&w.sb, "    }\n")
				default:
					fmt.Fprintf(&w.sb, "    {\n")
					fmt.Fprintf(&w.sb, "        auto _tmp = %s.value().to_bytes();\n", f.Name)
					fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());\n")
					fmt.Fprintf(&w.sb, "    }\n")
				}
			case ir.KindEnum:
				e := w.lookupEnum(f.Type.Ref)
				size := e.BackingType.Size()
				cppBacking := cppPrimitiveType(e.BackingType)
				valueExpr := fmt.Sprintf("static_cast<%s>(%s.value())", cppBacking, f.Name)
				w.writeWritePrimitive(valueExpr, cppBacking, size, isBig)
			case ir.KindPrimitive:
				w.writeCppPrimitiveWrite(f, isBig, lengthSources, countSources)
			}

			writeCode := w.sb.String()
			w.sb = orig

			for _, line := range strings.Split(writeCode, "\n") {
				if line == "" {
					continue
				}
				fmt.Fprintf(&w.sb, "    %s\n", line)
			}

			w.sb.WriteString("    }\n")
		} else {
			switch f.Type.Kind {
			case ir.KindMatch:
				w.writeMatchWrite(f, s, isBig)

			case ir.KindStruct:
				switch f.Type.Array.Kind {
				case ir.RestArray, ir.CountRef:
					fmt.Fprintf(&w.sb, "    for (const auto& _item : %s) {\n", f.Name)
					fmt.Fprintf(&w.sb, "        auto _tmp = _item.to_bytes();\n")
					fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());\n")
					fmt.Fprintf(&w.sb, "    }\n")
				default:
					fmt.Fprintf(&w.sb, "    {\n")
					fmt.Fprintf(&w.sb, "        auto _tmp = %s.to_bytes();\n", f.Name)
					fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());\n")
					fmt.Fprintf(&w.sb, "    }\n")
				}

			case ir.KindEnum:
				e := w.lookupEnum(f.Type.Ref)
				size := e.BackingType.Size()
				cppBacking := cppPrimitiveType(e.BackingType)

				valueExpr := fmt.Sprintf("static_cast<%s>(%s)", cppBacking, f.Name)
				if target, ok := lengthSources[f.Name]; ok {
					valueExpr = fmt.Sprintf("static_cast<%s>(%s.size())", cppBacking, target)
				} else if target, ok := countSources[f.Name]; ok {
					valueExpr = fmt.Sprintf("static_cast<%s>(%s.size())", cppBacking, target)
				}
				w.writeWritePrimitive(valueExpr, cppBacking, size, isBig)

			case ir.KindPrimitive:
				w.writeCppPrimitiveWrite(f, isBig, lengthSources, countSources)
			}
		}
	}

	fmt.Fprintf(&w.sb, "    return _buf;\n")
	fmt.Fprintf(&w.sb, "}\n")
}

func (w *writer) writeCppPrimitiveWrite(f *ir.Field, isBig bool, lengthSources, countSources map[string]string) {
	prim := f.Type.Primitive
	cppType := cppPrimitiveType(prim)

	valueExpr := f.Name
	if target, ok := lengthSources[f.Name]; ok {
		valueExpr = fmt.Sprintf("static_cast<%s>(%s.size())", cppType, target)
	} else if target, ok := countSources[f.Name]; ok {
		valueExpr = fmt.Sprintf("static_cast<%s>(%s.size())", cppType, target)
	}

	switch f.Type.Array.Kind {
	case ir.NotArray:
		if prim == ir.Bytes || prim == ir.String {
			// bare bytes - empty, nothing to write
		} else {
			size := prim.Size()
			w.writeWritePrimitive(valueExpr, cppType, size, isBig)
		}

	case ir.FixedSize:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "    _buf.insert(_buf.end(), %s.begin(), %s.end());\n", f.Name, f.Name)
			} else {
				fmt.Fprintf(&w.sb, "    _buf.insert(_buf.end(), %s, %s + %d);\n", f.Name, f.Name, f.Type.Array.FixedSize)
			}
		} else {
			size := prim.Size()
			fmt.Fprintf(&w.sb, "    for (const auto& _v : %s) {\n", f.Name)
			w.writeWritePrimitiveInner("_v", cppType, size, isBig)
			fmt.Fprintf(&w.sb, "    }\n")
		}

	case ir.LengthRef:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "    _buf.insert(_buf.end(), %s.begin(), %s.end());\n", f.Name, f.Name)
		} else {
			size := prim.Size()
			fmt.Fprintf(&w.sb, "    for (const auto& _v : %s) {\n", f.Name)
			w.writeWritePrimitiveInner("_v", cppType, size, isBig)
			fmt.Fprintf(&w.sb, "    }\n")
		}

	case ir.RestArray:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "    _buf.insert(_buf.end(), %s.begin(), %s.end());\n", f.Name, f.Name)
		} else {
			size := prim.Size()
			fmt.Fprintf(&w.sb, "    for (const auto& _v : %s) {\n", f.Name)
			w.writeWritePrimitiveInner("_v", cppType, size, isBig)
			fmt.Fprintf(&w.sb, "    }\n")
		}

	case ir.Terminator:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "    _buf.insert(_buf.end(), %s.begin(), %s.end());\n", f.Name, f.Name)
			fmt.Fprintf(&w.sb, "    _buf.push_back(%d);\n", f.Type.Array.Sentinel)
		} else {
			size := prim.Size()
			fmt.Fprintf(&w.sb, "    for (const auto& _v : %s) {\n", f.Name)
			w.writeWritePrimitiveInner("_v", cppType, size, isBig)
			fmt.Fprintf(&w.sb, "    }\n")
			w.writeWritePrimitive(fmt.Sprintf("static_cast<%s>(%d)", cppType, f.Type.Array.Sentinel), cppType, size, isBig)
		}

	case ir.FixedTerminator:
		fmt.Fprintf(&w.sb, "    {\n")
		fmt.Fprintf(&w.sb, "        std::vector<uint8_t> _tmp(%d, %d);\n", f.Type.Array.FixedSize, f.Type.Array.Sentinel)
		fmt.Fprintf(&w.sb, "        std::memcpy(_tmp.data(), %s.data(), std::min(%s.size(), static_cast<size_t>(%d)));\n", f.Name, f.Name, f.Type.Array.FixedSize)
		fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());\n")
		fmt.Fprintf(&w.sb, "    }\n")
	}
}

func (w *writer) writeWritePrimitive(valueExpr, cppType string, size int, isBig bool) {
	if size == 1 {
		fmt.Fprintf(&w.sb, "    _buf.push_back(static_cast<uint8_t>(%s));\n", valueExpr)
		return
	}
	fmt.Fprintf(&w.sb, "    {\n")
	if isBig {
		fmt.Fprintf(&w.sb, "        %s _tmp = swap%d(%s);\n", cppType, size*8, valueExpr)
	} else {
		fmt.Fprintf(&w.sb, "        %s _tmp = %s;\n", cppType, valueExpr)
	}
	fmt.Fprintf(&w.sb, "        uint8_t _raw[%d];\n", size)
	fmt.Fprintf(&w.sb, "        std::memcpy(_raw, &_tmp, %d);\n", size)
	fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _raw, _raw + %d);\n", size)
	fmt.Fprintf(&w.sb, "    }\n")
}

func (w *writer) writeWritePrimitiveInner(valueExpr, cppType string, size int, isBig bool) {
	if size == 1 {
		fmt.Fprintf(&w.sb, "        _buf.push_back(static_cast<uint8_t>(%s));\n", valueExpr)
		return
	}
	fmt.Fprintf(&w.sb, "        {\n")
	if isBig {
		fmt.Fprintf(&w.sb, "            %s _tmp = swap%d(%s);\n", cppType, size*8, valueExpr)
	} else {
		fmt.Fprintf(&w.sb, "            %s _tmp = %s;\n", cppType, valueExpr)
	}
	fmt.Fprintf(&w.sb, "            uint8_t _raw[%d];\n", size)
	fmt.Fprintf(&w.sb, "            std::memcpy(_raw, &_tmp, %d);\n", size)
	fmt.Fprintf(&w.sb, "            _buf.insert(_buf.end(), _raw, _raw + %d);\n", size)
	fmt.Fprintf(&w.sb, "        }\n")
}

func (w *writer) writeMatchWrite(f *ir.Field, _ *ir.Struct, isBig bool) {
	m := f.Match
	for i, c := range m.Cases {
		idx := w.variantIdx(m, &c.Type)
		if i == 0 {
			fmt.Fprintf(&w.sb, "    if (%s.index() == %d) {\n", f.Name, idx)
		} else {
			fmt.Fprintf(&w.sb, "    } else if (%s.index() == %d) {\n", f.Name, idx)
		}
		w.writeVariantCaseWrite(f.Name, &c.Type, idx, isBig)
	}

	if m.Default != nil {
		idx := w.variantIdx(m, m.Default)
		fmt.Fprintf(&w.sb, "    } else if (%s.index() == %d) {\n", f.Name, idx)
		w.writeVariantCaseWrite(f.Name, m.Default, idx, isBig)
	}
	w.sb.WriteString("    }\n")
}

func (w *writer) writeVariantCaseWrite(fieldName string, ft *ir.FieldType, variantIdx int, isBig bool) {
	switch ft.Kind {
	case ir.KindPrimitive:
		if ft.Primitive == ir.Bytes || ft.Primitive == ir.String {
			fmt.Fprintf(&w.sb, "        auto& _v = std::get<%d>(%s);\n", variantIdx, fieldName)
			fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _v.begin(), _v.end());\n")
		} else {
			cppType := cppPrimitiveType(ft.Primitive)
			size := ft.Primitive.Size()
			fmt.Fprintf(&w.sb, "        auto& _v = std::get<%d>(%s);\n", variantIdx, fieldName)
			if size == 1 {
				fmt.Fprintf(&w.sb, "        _buf.push_back(static_cast<uint8_t>(_v));\n")
			} else {
				if isBig {
					fmt.Fprintf(&w.sb, "        %s _tmp = swap%d(_v);\n", cppType, size*8)
				} else {
					fmt.Fprintf(&w.sb, "        %s _tmp = _v;\n", cppType)
				}
				fmt.Fprintf(&w.sb, "        uint8_t _raw[%d];\n", size)
				fmt.Fprintf(&w.sb, "        std::memcpy(_raw, &_tmp, %d);\n", size)
				fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _raw, _raw + %d);\n", size)
			}
		}
	case ir.KindEnum:
		e := w.lookupEnum(ft.Ref)
		cppBacking := cppPrimitiveType(e.BackingType)
		size := e.BackingType.Size()
		fmt.Fprintf(&w.sb, "        auto _v = static_cast<%s>(std::get<%d>(%s));\n", cppBacking, variantIdx, fieldName)
		if size == 1 {
			fmt.Fprintf(&w.sb, "        _buf.push_back(static_cast<uint8_t>(_v));\n")
		} else {
			if isBig {
				fmt.Fprintf(&w.sb, "        _v = swap%d(_v);\n", size*8)
			}
			fmt.Fprintf(&w.sb, "        uint8_t _raw[%d];\n", size)
			fmt.Fprintf(&w.sb, "        std::memcpy(_raw, &_v, %d);\n", size)
			fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _raw, _raw + %d);\n", size)
		}
	case ir.KindStruct:
		fmt.Fprintf(&w.sb, "        auto _tmp = std::get<%d>(%s).to_bytes();\n", variantIdx, fieldName)
		fmt.Fprintf(&w.sb, "        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());\n")
	}
}

func (w *writer) writeReadPrimitive(target, cppType string, size int, isBig bool, direct bool) {
	if size == 1 {
		fmt.Fprintf(&w.sb, "    if (offset + 1 > len) throw std::runtime_error(\"buffer overflow\");\n")
		if direct {
			fmt.Fprintf(&w.sb, "    %s = static_cast<%s>(buf[offset]);\n", target, cppType)
		} else {
			fmt.Fprintf(&w.sb, "    %s %s = static_cast<%s>(buf[offset]);\n", cppType, target, cppType)
		}
		w.sb.WriteString("    offset += 1;\n")
		return
	}

	fmt.Fprintf(&w.sb, "    if (offset + %d > len) throw std::runtime_error(\"buffer overflow\");\n", size)
	if direct {
		fmt.Fprintf(&w.sb, "    std::memcpy(&%s, buf + offset, %d);\n", target, size)
		if isBig {
			fmt.Fprintf(&w.sb, "    %s = swap%d(%s);\n", target, size*8, target)
		}
	} else {
		fmt.Fprintf(&w.sb, "    %s %s;\n", cppType, target)
		fmt.Fprintf(&w.sb, "    std::memcpy(&%s, buf + offset, %d);\n", target, size)
		if isBig {
			fmt.Fprintf(&w.sb, "    %s = swap%d(%s);\n", target, size*8, target)
		}
	}
	fmt.Fprintf(&w.sb, "    offset += %d;\n", size)
}

func (w *writer) writeReadPrimitiveInner(varName, cppType string, size int, isBig bool) {
	if size == 1 {
		fmt.Fprintf(&w.sb, "        if (offset + 1 > len) throw std::runtime_error(\"buffer overflow\");\n")
		fmt.Fprintf(&w.sb, "        %s = static_cast<%s>(buf[offset]);\n", varName, cppType)
		w.sb.WriteString("        offset += 1;\n")
		return
	}
	fmt.Fprintf(&w.sb, "        if (offset + %d > len) throw std::runtime_error(\"buffer overflow\");\n", size)
	fmt.Fprintf(&w.sb, "        std::memcpy(&%s, buf + offset, %d);\n", varName, size)
	if isBig {
		fmt.Fprintf(&w.sb, "        %s = swap%d(%s);\n", varName, size*8, varName)
	}
	fmt.Fprintf(&w.sb, "        offset += %d;\n", size)
}

func (w *writer) writeEndianHelper(size int) {
	bits := size * 8
	cppType := ""
	switch size {
	case 2:
		cppType = "uint16_t"
	case 4:
		cppType = "uint32_t"
	case 8:
		cppType = "uint64_t"
	}
	fmt.Fprintf(&w.sb, "\ntemplate <typename T>\nT swap%d(T val) {\n", bits)
	fmt.Fprintf(&w.sb, "    %s v;\n", cppType)
	w.sb.WriteString("    std::memcpy(&v, &val, sizeof(v));\n")

	switch size {
	case 2:
		w.sb.WriteString("    v = (v >> 8) | (v << 8);\n")
	case 4:
		w.sb.WriteString("    v = ((v >> 24) & 0xFF) | ((v >> 8) & 0xFF00) | ((v << 8) & 0xFF0000) | ((v << 24) & 0xFF000000);\n")
	case 8:
		w.sb.WriteString("    v = ((v >> 56) & 0xFFULL) | ((v >> 40) & 0xFF00ULL) | ((v >> 24) & 0xFF0000ULL) |\n")
		w.sb.WriteString("        ((v >> 8) & 0xFF000000ULL) | ((v << 8) & 0xFF00000000ULL) |\n")
		w.sb.WriteString("        ((v << 24) & 0xFF0000000000ULL) | ((v << 40) & 0xFF000000000000ULL) |\n")
		w.sb.WriteString("        ((v << 56) & 0xFF00000000000000ULL);\n")
	}

	w.sb.WriteString("    T out;\n")
	w.sb.WriteString("    std::memcpy(&out, &v, sizeof(out));\n")
	w.sb.WriteString("    return out;\n")
	w.sb.WriteString("}\n")
}

func (w *writer) writeBytesJSON(f *ir.Field) {
	if f.Type.Array.Kind == ir.FixedSize {
		w.sb.WriteString("    s += \"[\";\n")
		fmt.Fprintf(&w.sb, "    for (size_t i = 0; i < %d; ++i) {\n", f.Type.Array.FixedSize)
		w.sb.WriteString("        if (i > 0) s += \",\";\n")
		fmt.Fprintf(&w.sb, "        s += std::to_string(%s[i]);\n", f.Name)
		w.sb.WriteString("    }\n")
		w.sb.WriteString("    s += \"]\";\n")
	} else {
		w.sb.WriteString("    s += \"[\";\n")
		fmt.Fprintf(&w.sb, "    for (size_t i = 0; i < %s.size(); ++i) {\n", f.Name)
		w.sb.WriteString("        if (i > 0) s += \",\";\n")
		fmt.Fprintf(&w.sb, "        s += std::to_string(%s[i]);\n", f.Name)
		w.sb.WriteString("    }\n")
		w.sb.WriteString("    s += \"]\";\n")
	}
}

func (w *writer) writeBytesJSONWithIndent(f *ir.Field, accessName, indent string) {
	if f.Type.Array.Kind == ir.FixedSize {
		fmt.Fprintf(&w.sb, "%ss += \"[\";\n", indent)
		fmt.Fprintf(&w.sb, "%sfor (size_t i = 0; i < %d; ++i) {\n", indent, f.Type.Array.FixedSize)
		fmt.Fprintf(&w.sb, "%s    if (i > 0) s += \",\";\n", indent)
		fmt.Fprintf(&w.sb, "%s    s += std::to_string(%s[i]);\n", indent, accessName)
		fmt.Fprintf(&w.sb, "%s}\n", indent)
		fmt.Fprintf(&w.sb, "%ss += \"]\";\n", indent)
	} else {
		fmt.Fprintf(&w.sb, "%ss += \"[\";\n", indent)
		fmt.Fprintf(&w.sb, "%sfor (size_t i = 0; i < %s.size(); ++i) {\n", indent, accessName)
		fmt.Fprintf(&w.sb, "%s    if (i > 0) s += \",\";\n", indent)
		fmt.Fprintf(&w.sb, "%s    s += std::to_string(%s[i]);\n", indent, accessName)
		fmt.Fprintf(&w.sb, "%s}\n", indent)
		fmt.Fprintf(&w.sb, "%ss += \"]\";\n", indent)
	}
}

func (w *writer) collectEndianSizes() map[int]bool {
	sizes := make(map[int]bool)
	for _, s := range w.pkg.Structs {
		for _, f := range s.Fields {
			endian := f.EffectiveEndian(s.Options.Endian)
			if endian != ir.BigEndian {
				continue
			}
			if f.Type.Kind == ir.KindMatch && f.Match != nil {
				w.collectMatchEndianSizes(f.Match, sizes)
				continue
			}
			size := 0
			switch f.Type.Kind {
			case ir.KindPrimitive:
				size = f.Type.Primitive.Size()
			case ir.KindEnum:
				e := w.lookupEnum(f.Type.Ref)
				if e != nil {
					size = e.BackingType.Size()
				}
			}
			if size > 1 {
				sizes[size] = true
			}
		}
	}
	return sizes
}

func (w *writer) collectMatchEndianSizes(m *ir.MatchSpec, sizes map[int]bool) {
	collectFT := func(ft *ir.FieldType) {
		size := 0
		switch ft.Kind {
		case ir.KindPrimitive:
			size = ft.Primitive.Size()
		case ir.KindEnum:
			e := w.lookupEnum(ft.Ref)
			if e != nil {
				size = e.BackingType.Size()
			}
		}
		if size > 1 {
			sizes[size] = true
		}
	}
	for _, c := range m.Cases {
		collectFT(&c.Type)
	}
	if m.Default != nil {
		collectFT(m.Default)
	}
}

func (w *writer) lookupEnum(name string) *ir.Enum {
	for _, e := range w.pkg.Enums {
		if e.Name == name {
			return e
		}
	}
	return nil
}

func structHasCrossRefs(s *ir.Struct) bool {
	for _, f := range s.Fields {
		if f.CrossRef != "" {
			return true
		}
	}
	return false
}

func emitCppExpr(expr *ir.ExprNode, thisName string) string {
	switch expr.Kind {
	case ir.ExprLiteral:
		if expr.Literal.Int != nil {
			return fmt.Sprintf("%d", *expr.Literal.Int)
		}
		if expr.Literal.Bool != nil {
			if *expr.Literal.Bool {
				return "true"
			}
			return "false"
		}
		if expr.Literal.Str != nil {
			return fmt.Sprintf("%q", *expr.Literal.Str)
		}
		if expr.Literal.Float != nil {
			return fmt.Sprintf("%g", *expr.Literal.Float)
		}
		return "0"

	case ir.ExprIdent:
		if expr.Ident == "this" {
			return thisName
		}
		return "result." + expr.Ident

	case ir.ExprBinary:
		return fmt.Sprintf("(%s %s %s)", emitCppExpr(expr.Left, thisName), expr.Op, emitCppExpr(expr.Right, thisName))

	case ir.ExprUnary:
		return fmt.Sprintf("(%s%s)", expr.Op, emitCppExpr(expr.Operand, thisName))

	case ir.ExprSelect:
		return fmt.Sprintf("%s.%s", emitCppExpr(expr.Operand, thisName), expr.Field)

	case ir.ExprCall:
		switch expr.FuncName {
		case "size":
			if expr.IsMember {
				return fmt.Sprintf("%s.size()", emitCppExpr(expr.Operand, thisName))
			}
			if len(expr.Args) > 0 {
				return fmt.Sprintf("%s.size()", emitCppExpr(expr.Args[0], thisName))
			}
			return "0"
		case "has":
			if len(expr.Args) > 0 && expr.Args[0].Kind == ir.ExprSelect {
				return fmt.Sprintf("%s.%s.has_value()", emitCppExpr(expr.Args[0].Operand, thisName), expr.Args[0].Field)
			}
			return "false"
		case "startsWith":
			if expr.IsMember && len(expr.Args) > 0 {
				op := emitCppExpr(expr.Operand, thisName)
				arg := emitCppExpr(expr.Args[0], thisName)
				return fmt.Sprintf("%s.substr(0, %s.size()) == %s", op, arg, arg)
			}
		case "endsWith":
			if expr.IsMember && len(expr.Args) > 0 {
				op := emitCppExpr(expr.Operand, thisName)
				arg := emitCppExpr(expr.Args[0], thisName)
				return fmt.Sprintf("%s.compare(%s.size()-%s.size(), %s.size(), %s) == 0", op, op, arg, arg, arg)
			}
		case "contains":
			if expr.IsMember && len(expr.Args) > 0 {
				op := emitCppExpr(expr.Operand, thisName)
				arg := emitCppExpr(expr.Args[0], thisName)
				return fmt.Sprintf("%s.find(%s) != std::string::npos", op, arg)
			}
		case "matches":
			if expr.IsMember && len(expr.Args) > 0 {
				op := emitCppExpr(expr.Operand, thisName)
				arg := emitCppExpr(expr.Args[0], thisName)
				return fmt.Sprintf("std::regex_search(%s, std::regex(%s))", op, arg)
			}
		}

		if expr.IsMember {
			op := emitCppExpr(expr.Operand, thisName)
			var args []string
			for _, a := range expr.Args {
				args = append(args, emitCppExpr(a, thisName))
			}
			return fmt.Sprintf("%s.%s(%s)", op, expr.FuncName, strings.Join(args, ", "))
		}

		var args []string
		for _, a := range expr.Args {
			args = append(args, emitCppExpr(a, thisName))
		}
		return fmt.Sprintf("%s(%s)", expr.FuncName, strings.Join(args, ", "))
	}
	return "0"
}

func buildAutoComputeMap(s *ir.Struct) (lengthSources, countSources map[string]string) {
	lengthSources = make(map[string]string)
	countSources = make(map[string]string)
	for _, f := range s.Fields {
		if f.Type.Array.Kind == ir.LengthRef {
			lengthSources[f.Type.Array.LengthRef] = f.Name
		}
		if f.Type.Array.Kind == ir.CountRef && !strings.Contains(f.Type.Array.CountRef, ".") {
			countSources[f.Type.Array.CountRef] = f.Name
		}
	}
	return
}

func cppFieldPrimitiveType(f *ir.Field) string {
	prim := f.Type.Primitive
	cppType := cppPrimitiveType(prim)

	switch f.Type.Array.Kind {
	case ir.NotArray:
		return cppType
	case ir.FixedSize:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				return "std::string"
			}
			return fmt.Sprintf("uint8_t[%d]", f.Type.Array.FixedSize)
		}
		return fmt.Sprintf("std::vector<%s>", cppType)
	case ir.FixedTerminator:
		return "std::string"
	case ir.LengthRef, ir.RestArray, ir.Terminator:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				return "std::string"
			}
			return "std::vector<uint8_t>"
		}
		return fmt.Sprintf("std::vector<%s>", cppType)
	}
	return cppType
}

func cppFieldType(f *ir.Field) string {
	switch f.Type.Kind {
	case ir.KindStruct:
		if f.Type.Array.Kind == ir.RestArray || f.Type.Array.Kind == ir.CountRef {
			return fmt.Sprintf("std::vector<%s>", f.Type.Ref)
		}
		return f.Type.Ref
	case ir.KindEnum:
		return f.Type.Ref
	case ir.KindPrimitive:
		return cppFieldPrimitiveType(f)
	}
	return "uint8_t"
}

func cppTypeForFieldType(ft *ir.FieldType) string {
	switch ft.Kind {
	case ir.KindPrimitive:
		if ft.Primitive == ir.Bytes || ft.Primitive == ir.String {
			if ft.Array.Kind == ir.FixedSize {
				return "std::vector<uint8_t>"
			}
			return "std::vector<uint8_t>"
		}
		return cppPrimitiveType(ft.Primitive)
	case ir.KindEnum:
		return ft.Ref
	case ir.KindStruct:
		return ft.Ref
	}
	return "uint8_t"
}

func cppPrimitiveType(prim ir.PrimitiveType) string {
	switch prim {
	case ir.U8:
		return "uint8_t"
	case ir.U16:
		return "uint16_t"
	case ir.U32:
		return "uint32_t"
	case ir.U64:
		return "uint64_t"
	case ir.I8:
		return "int8_t"
	case ir.I16:
		return "int16_t"
	case ir.I32:
		return "int32_t"
	case ir.I64:
		return "int64_t"
	case ir.F32:
		return "float"
	case ir.F64:
		return "double"
	case ir.Bytes, ir.String:
		return "uint8_t"
	default:
		return "uint8_t"
	}
}
