// Package rust generates Rust parsers from Cleave IR packages.
package rust

import (
	"errors"
	"fmt"
	"path"
	"strings"

	"github.com/rdeusser/cleave/internal/codegen"
	"github.com/rdeusser/cleave/internal/ir"
)

// Generator emits an include-safe Rust module and, by default, a Cargo crate.
type Generator struct {
	// NoCargo emits one Rust source file instead of a Cargo crate.
	NoCargo bool
}

// Generate emits Rust files for pkg.
func (g *Generator) Generate(pkg *ir.Package) ([]codegen.OutputFile, error) {
	if pkg == nil {
		return nil, errors.New("rust codegen: nil package")
	}

	w, err := newWriter(pkg)
	if err != nil {
		return nil, err
	}
	if err := w.source(); err != nil {
		return nil, err
	}
	source := []byte(w.sb.String())
	packageName := strings.ToLower(pkg.Name)
	if g.NoCargo {
		return []codegen.OutputFile{{
			Name:    packageName + ".rs",
			Content: source,
		}}, nil
	}

	return []codegen.OutputFile{
		{
			Name:    path.Join(packageName, "Cargo.toml"),
			Content: []byte(cargoManifest(packageName, w.requirements)),
		},
		{
			Name:    path.Join(packageName, "src", "lib.rs"),
			Content: source,
		},
	}, nil
}

type writer struct {
	sb           strings.Builder
	pkg          *ir.Package
	matches      []*matchType
	matchFor     map[*ir.Field]*matchType
	requirements requirements
}

func newWriter(pkg *ir.Package) (*writer, error) {
	w := &writer{
		pkg:          pkg,
		matchFor:     make(map[*ir.Field]*matchType),
		requirements: analyzeRequirements(pkg),
	}
	if err := w.prepareMatches(); err != nil {
		return nil, err
	}
	if err := w.validateNames(); err != nil {
		return nil, err
	}
	return w, nil
}

func (w *writer) source() error {
	w.sb.WriteString("// Generated by cleave. Do not edit.\n")
	fmt.Fprintf(&w.sb, "// Package: %s\n", w.pkg.Name)
	if !w.requirements.hasLegacyEncoding && !w.requirements.hasRegex {
		w.sb.WriteString("// Cargo dependencies: none.\n")
	} else {
		w.sb.WriteString("// Cargo dependencies:\n")
		if w.requirements.hasLegacyEncoding {
			w.sb.WriteString("// - encoding_rs = \"0.8.35\"\n")
		}
		if w.requirements.hasRegex {
			w.sb.WriteString("// - regex = \"1.13.1\"\n")
		}
	}
	w.sb.WriteString("\n")
	w.writePreludeImports()
	w.writeRuntime()
	w.sb.WriteString("\n")
	return w.writeDeclarations()
}

func (w *writer) writePreludeImports() {
	wroteImport := false
	if len(w.pkg.Enums) > 0 && w.hasTypeName("Into") {
		w.sb.WriteString("use ::std::convert::Into as _;\n")
		wroteImport = true
	}
	if w.hasTypeName("TryFrom") {
		w.sb.WriteString("use ::std::convert::TryFrom as _;\n")
		wroteImport = true
	}
	if wroteImport {
		w.sb.WriteString("\n")
	}
}

func (w *writer) hasTypeName(name string) bool {
	for _, enum := range w.pkg.Enums {
		if rustIdent(enum.Name) == name {
			return true
		}
	}
	for _, structure := range w.pkg.Structs {
		if rustIdent(structure.Name) == name {
			return true
		}
	}
	for _, match := range w.matches {
		if match.name == name {
			return true
		}
	}
	return false
}

func cargoManifest(name string, requirements requirements) string {
	var sb strings.Builder
	sb.WriteString("# Generated by cleave. Do not edit.\n\n")
	sb.WriteString("[package]\n")
	fmt.Fprintf(&sb, "name = %q\n", name)
	sb.WriteString("version = \"0.0.0\"\n")
	sb.WriteString("edition = \"2024\"\n")
	sb.WriteString("publish = false\n\n")
	if requirements.hasLegacyEncoding || requirements.hasRegex {
		sb.WriteString("[dependencies]\n")
		if requirements.hasLegacyEncoding {
			sb.WriteString("encoding_rs = \"0.8.35\"\n")
		}
		if requirements.hasRegex {
			sb.WriteString("regex = \"1.13.1\"\n")
		}
		sb.WriteString("\n")
	}
	sb.WriteString("[lints.clippy]\n")
	sb.WriteString("all = { level = \"warn\", priority = -1 }\n")
	sb.WriteString("pedantic = { level = \"warn\", priority = -1 }\n")
	sb.WriteString("unwrap_used = \"warn\"\n")
	sb.WriteString("expect_used = \"warn\"\n")
	sb.WriteString("indexing_slicing = \"warn\"\n")
	sb.WriteString("undocumented_unsafe_blocks = \"warn\"\n")
	sb.WriteString("allow_attributes_without_reason = \"warn\"\n")
	sb.WriteString("clone_on_ref_ptr = \"warn\"\n")
	sb.WriteString("rc_mutex = \"warn\"\n")
	sb.WriteString("dbg_macro = \"warn\"\n")
	sb.WriteString("module_name_repetitions = \"allow\"\n")
	sb.WriteString("must_use_candidate = \"allow\"\n")
	sb.WriteString("missing_errors_doc = \"allow\"\n")
	sb.WriteString("missing_panics_doc = \"allow\"\n")
	return sb.String()
}
