package python

import (
	"fmt"
	"strings"

	"github.com/rdeusser/cleave/internal/codegen"
	"github.com/rdeusser/cleave/internal/ir"
)

type Generator struct{}

func (g *Generator) Generate(pkg *ir.Package) ([]codegen.OutputFile, error) {
	w := &writer{pkg: pkg}
	w.generate()

	return []codegen.OutputFile{{
		Name:    pkg.Name + ".py",
		Content: []byte(w.sb.String()),
	}}, nil
}

type writer struct {
	sb  strings.Builder
	pkg *ir.Package
}

func (w *writer) generate() {
	w.sb.WriteString("\"\"\"Generated by cleave. Do not edit.\"\"\"\n\n")
	w.sb.WriteString("from __future__ import annotations\n\n")
	w.sb.WriteString("import enum\n")
	w.sb.WriteString("import json\n")
	w.sb.WriteString("import struct\n")
	w.sb.WriteString("from dataclasses import dataclass\n")

	needsOptional := w.needsOptionalImport()
	needsClassVar := w.needsClassVarImport()
	if needsOptional && needsClassVar {
		w.sb.WriteString("from typing import ClassVar, Optional\n")
	} else if needsOptional {
		w.sb.WriteString("from typing import Optional\n")
	} else if needsClassVar {
		w.sb.WriteString("from typing import ClassVar\n")
	}

	for _, e := range w.pkg.Enums {
		w.sb.WriteString("\n\n")
		w.writeEnum(e)
	}

	for _, s := range w.pkg.Structs {
		w.sb.WriteString("\n\n")
		w.writeStruct(s)
	}

	w.sb.WriteString("\n")
}

func (w *writer) needsOptionalImport() bool {
	for _, s := range w.pkg.Structs {
		for _, f := range s.Fields {
			if f.Condition != nil {
				return true
			}
		}
	}
	return false
}

func (w *writer) needsClassVarImport() bool {
	for _, s := range w.pkg.Structs {
		for _, f := range s.Fields {
			if f.CrossRef != "" {
				return true
			}
		}
	}
	return false
}

func (w *writer) writeEnum(e *ir.Enum) {
	fmt.Fprintf(&w.sb, "class %s(enum.IntEnum):\n", e.Name)
	for _, v := range e.Variants {
		fmt.Fprintf(&w.sb, "    %s = %d\n", v.Name, v.Value)
	}
}

func (w *writer) writeStruct(s *ir.Struct) {
	fmt.Fprintf(&w.sb, "@dataclass\n")
	fmt.Fprintf(&w.sb, "class %s:\n", s.Name)

	for _, f := range s.Fields {
		fmt.Fprintf(&w.sb, "    %s: %s\n", f.Name, w.pythonType(f))
	}

	// Emit _REFS class variable for fields with cross-format references.
	var refs []string
	for _, f := range s.Fields {
		if f.CrossRef != "" {
			refs = append(refs, fmt.Sprintf("        %q: %q,\n", f.Name, f.CrossRef))
		}
	}
	if len(refs) > 0 {
		w.sb.WriteString("\n    _REFS: ClassVar[dict[str, str]] = {\n")
		for _, r := range refs {
			w.sb.WriteString(r)
		}
		w.sb.WriteString("    }\n")
	}

	w.sb.WriteString("\n")
	w.writeParseMethod(s)
	w.sb.WriteString("\n")
	w.writeToJSON(s)
	w.sb.WriteString("\n")
	w.writeToBytes(s)
}

func (w *writer) writeParseMethod(s *ir.Struct) {
	fmt.Fprintf(&w.sb, "    @classmethod\n")
	fmt.Fprintf(&w.sb, "    def parse(cls, buf: bytes, offset: int = 0) -> tuple[\"%s\", int]:\n", s.Name)

	for _, f := range s.Fields {
		readCode := w.captureFieldRead(f, s)

		if f.Condition != nil {
			condExpr := emitPythonExpr(f.Condition, "")
			fmt.Fprintf(&w.sb, "        if %s:\n", condExpr)
			w.sb.WriteString(indentLines(readCode, "    "))
			for _, v := range f.Validations {
				valExpr := emitPythonExpr(v.Expression, f.Name)
				fmt.Fprintf(&w.sb, "            if not %s:\n", valExpr)
				fmt.Fprintf(&w.sb, "                raise ValueError(%q)\n", v.Message)
			}
			fmt.Fprintf(&w.sb, "        else:\n")
			fmt.Fprintf(&w.sb, "            %s = None\n", f.Name)
		} else {
			w.sb.WriteString(readCode)
			for _, v := range f.Validations {
				valExpr := emitPythonExpr(v.Expression, f.Name)
				fmt.Fprintf(&w.sb, "        if not %s:\n", valExpr)
				fmt.Fprintf(&w.sb, "            raise ValueError(%q)\n", v.Message)
			}
		}
	}

	w.sb.WriteString("        return cls(\n")
	for _, f := range s.Fields {
		fmt.Fprintf(&w.sb, "            %s=%s,\n", f.Name, f.Name)
	}
	w.sb.WriteString("        ), offset\n")
}

func (w *writer) captureFieldRead(f *ir.Field, s *ir.Struct) string {
	var buf strings.Builder
	saved := w.sb
	w.sb = buf

	endian := f.EffectiveEndian(s.Options.Endian)
	prefix := endianPrefix(endian)

	switch {
	case f.Type.Kind == ir.KindMatch:
		w.writeMatchParse(f, s, prefix)
	case f.Type.Kind == ir.KindStruct:
		switch f.Type.Array.Kind {
		case ir.RestArray:
			fmt.Fprintf(&w.sb, "        %s = []\n", f.Name)
			fmt.Fprintf(&w.sb, "        while offset < len(buf):\n")
			fmt.Fprintf(&w.sb, "            _item, offset = %s.parse(buf, offset)\n", f.Type.Ref)
			fmt.Fprintf(&w.sb, "            %s.append(_item)\n", f.Name)
		case ir.CountRef:
			fmt.Fprintf(&w.sb, "        %s = []\n", f.Name)
			fmt.Fprintf(&w.sb, "        for _ in range(%s):\n", f.Type.Array.CountRef)
			fmt.Fprintf(&w.sb, "            _item, offset = %s.parse(buf, offset)\n", f.Type.Ref)
			fmt.Fprintf(&w.sb, "            %s.append(_item)\n", f.Name)
		default:
			fmt.Fprintf(&w.sb, "        %s, offset = %s.parse(buf, offset)\n", f.Name, f.Type.Ref)
		}
	case f.Type.Kind == ir.KindEnum:
		e := w.lookupEnum(f.Type.Ref)
		fmtStr := structFormat(e.BackingType)
		size := e.BackingType.Size()
		fmt.Fprintf(&w.sb, "        %s = %s(struct.unpack_from(\"%s%s\", buf, offset)[0])\n",
			f.Name, f.Type.Ref, prefix, fmtStr)
		fmt.Fprintf(&w.sb, "        offset += %d\n", size)
	case f.Type.Kind == ir.KindPrimitive:
		w.writePrimitiveRead(f, prefix)
	}

	result := w.sb.String()
	w.sb = saved
	return result
}

func (w *writer) writeMatchParse(f *ir.Field, s *ir.Struct, prefix string) {
	m := f.Match
	for i, c := range m.Cases {
		if i == 0 {
			fmt.Fprintf(&w.sb, "        if %s == %d:\n", m.TagField, c.Value)
		} else {
			fmt.Fprintf(&w.sb, "        elif %s == %d:\n", m.TagField, c.Value)
		}
		w.writeTypeParse(f.Name, &c.Type, prefix, "            ")
	}

	if m.Default != nil {
		w.sb.WriteString("        else:\n")
		w.writeTypeParse(f.Name, m.Default, prefix, "            ")
	} else {
		w.sb.WriteString("        else:\n")
		fmt.Fprintf(&w.sb, "            raise ValueError(f\"unknown tag value {%s} for %s.%s\")\n", m.TagField, s.Name, f.Name)
	}
}

func (w *writer) writeTypeParse(varName string, ft *ir.FieldType, prefix string, indent string) {
	switch ft.Kind {
	case ir.KindPrimitive:
		if ft.Primitive == ir.Bytes || ft.Primitive == ir.String {
			if ft.Array.Kind == ir.FixedSize {
				fmt.Fprintf(&w.sb, "%s%s = buf[offset:offset + %d]\n", indent, varName, ft.Array.FixedSize)
				fmt.Fprintf(&w.sb, "%soffset += %d\n", indent, ft.Array.FixedSize)
			} else {
				fmt.Fprintf(&w.sb, "%s%s = b\"\"\n", indent, varName)
			}
		} else {
			fmtStr := structFormat(ft.Primitive)
			size := ft.Primitive.Size()
			fmt.Fprintf(&w.sb, "%s%s = struct.unpack_from(\"%s%s\", buf, offset)[0]\n", indent, varName, prefix, fmtStr)
			fmt.Fprintf(&w.sb, "%soffset += %d\n", indent, size)
		}
	case ir.KindEnum:
		e := w.lookupEnum(ft.Ref)
		fmtStr := structFormat(e.BackingType)
		size := e.BackingType.Size()
		fmt.Fprintf(&w.sb, "%s%s = %s(struct.unpack_from(\"%s%s\", buf, offset)[0])\n", indent, varName, ft.Ref, prefix, fmtStr)
		fmt.Fprintf(&w.sb, "%soffset += %d\n", indent, size)
	case ir.KindStruct:
		fmt.Fprintf(&w.sb, "%s%s, offset = %s.parse(buf, offset)\n", indent, varName, ft.Ref)
	}
}

func (w *writer) writePrimitiveRead(f *ir.Field, prefix string) {
	prim := f.Type.Primitive

	switch f.Type.Array.Kind {
	case ir.NotArray:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "        %s = b\"\"\n", f.Name)
		} else {
			fmtStr := structFormat(prim)
			size := prim.Size()
			fmt.Fprintf(&w.sb, "        %s = struct.unpack_from(\"%s%s\", buf, offset)[0]\n",
				f.Name, prefix, fmtStr)
			fmt.Fprintf(&w.sb, "        offset += %d\n", size)
		}

	case ir.FixedSize:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "        %s = buf[offset:offset + %d]\n", f.Name, f.Type.Array.FixedSize)
			fmt.Fprintf(&w.sb, "        offset += %d\n", f.Type.Array.FixedSize)
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "        %s = %s.decode(\"%s\")\n", f.Name, f.Name, f.Encoding)
			}
		} else {
			fmtStr := structFormat(prim)
			size := prim.Size()
			fmt.Fprintf(&w.sb, "        %s = []\n", f.Name)
			fmt.Fprintf(&w.sb, "        for _ in range(%d):\n", f.Type.Array.FixedSize)
			fmt.Fprintf(&w.sb, "            %s.append(struct.unpack_from(\"%s%s\", buf, offset)[0])\n",
				f.Name, prefix, fmtStr)
			fmt.Fprintf(&w.sb, "            offset += %d\n", size)
		}

	case ir.LengthRef:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "        %s = buf[offset:offset + %s]\n", f.Name, f.Type.Array.LengthRef)
			fmt.Fprintf(&w.sb, "        offset += %s\n", f.Type.Array.LengthRef)
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "        %s = %s.decode(\"%s\")\n", f.Name, f.Name, f.Encoding)
			}
		} else {
			fmtStr := structFormat(prim)
			size := prim.Size()
			fmt.Fprintf(&w.sb, "        %s = []\n", f.Name)
			fmt.Fprintf(&w.sb, "        for _ in range(%s):\n", f.Type.Array.LengthRef)
			fmt.Fprintf(&w.sb, "            %s.append(struct.unpack_from(\"%s%s\", buf, offset)[0])\n",
				f.Name, prefix, fmtStr)
			fmt.Fprintf(&w.sb, "            offset += %d\n", size)
		}

	case ir.RestArray:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "        %s = buf[offset:]\n", f.Name)
			fmt.Fprintf(&w.sb, "        offset = len(buf)\n")
		} else {
			fmtStr := structFormat(prim)
			size := prim.Size()
			fmt.Fprintf(&w.sb, "        %s = []\n", f.Name)
			fmt.Fprintf(&w.sb, "        while offset < len(buf):\n")
			fmt.Fprintf(&w.sb, "            %s.append(struct.unpack_from(\"%s%s\", buf, offset)[0])\n",
				f.Name, prefix, fmtStr)
			fmt.Fprintf(&w.sb, "            offset += %d\n", size)
		}

	case ir.Terminator:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "        _start = offset\n")
			fmt.Fprintf(&w.sb, "        while offset < len(buf) and buf[offset] != %d:\n", f.Type.Array.Sentinel)
			fmt.Fprintf(&w.sb, "            offset += 1\n")
			fmt.Fprintf(&w.sb, "        %s = buf[_start:offset]\n", f.Name)
			fmt.Fprintf(&w.sb, "        if offset < len(buf):\n")
			fmt.Fprintf(&w.sb, "            offset += 1  # skip sentinel\n")
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "        %s = %s.decode(\"%s\")\n", f.Name, f.Name, f.Encoding)
			}
		} else {
			fmtStr := structFormat(prim)
			size := prim.Size()
			fmt.Fprintf(&w.sb, "        %s = []\n", f.Name)
			fmt.Fprintf(&w.sb, "        while offset < len(buf):\n")
			fmt.Fprintf(&w.sb, "            _val = struct.unpack_from(\"%s%s\", buf, offset)[0]\n", prefix, fmtStr)
			fmt.Fprintf(&w.sb, "            offset += %d\n", size)
			fmt.Fprintf(&w.sb, "            if _val == %d:\n", f.Type.Array.Sentinel)
			fmt.Fprintf(&w.sb, "                break\n")
			fmt.Fprintf(&w.sb, "            %s.append(_val)\n", f.Name)
		}

	case ir.FixedTerminator:
		enc := "utf-8"
		if f.Encoding != "" {
			enc = f.Encoding
		}
		fmt.Fprintf(&w.sb, "        _raw = buf[offset:offset + %d]\n", f.Type.Array.FixedSize)
		fmt.Fprintf(&w.sb, "        offset += %d\n", f.Type.Array.FixedSize)
		fmt.Fprintf(&w.sb, "        _end = _raw.find(%d)\n", f.Type.Array.Sentinel)
		fmt.Fprintf(&w.sb, "        %s = _raw[:_end].decode(\"%s\") if _end >= 0 else _raw.decode(\"%s\")\n", f.Name, enc, enc)
	}
}

func (w *writer) writeToJSON(s *ir.Struct) {
	fmt.Fprintf(&w.sb, "    def to_json(self) -> str:\n")
	fmt.Fprintf(&w.sb, "        return json.dumps(self._to_dict())\n")
	w.sb.WriteString("\n")
	fmt.Fprintf(&w.sb, "    def _to_dict(self) -> dict:\n")
	fmt.Fprintf(&w.sb, "        d = {}\n")

	for _, f := range s.Fields {
		if f.Condition != nil {
			fmt.Fprintf(&w.sb, "        if self.%s is not None:\n", f.Name)
			w.writeFieldToDict(f, "            ")
			fmt.Fprintf(&w.sb, "        else:\n")
			fmt.Fprintf(&w.sb, "            d[\"%s\"] = None\n", f.Name)
		} else {
			w.writeFieldToDict(f, "        ")
		}
	}

	fmt.Fprintf(&w.sb, "        return d\n")
}

func (w *writer) writeFieldToDict(f *ir.Field, indent string) {
	switch {
	case f.Type.Kind == ir.KindMatch:
		fmt.Fprintf(&w.sb, "%sif hasattr(self.%s, '_to_dict'):\n", indent, f.Name)
		fmt.Fprintf(&w.sb, "%s    d[\"%s\"] = self.%s._to_dict()\n", indent, f.Name, f.Name)
		fmt.Fprintf(&w.sb, "%selif isinstance(self.%s, bytes):\n", indent, f.Name)
		fmt.Fprintf(&w.sb, "%s    d[\"%s\"] = list(self.%s)\n", indent, f.Name, f.Name)
		fmt.Fprintf(&w.sb, "%selif isinstance(self.%s, enum.IntEnum):\n", indent, f.Name)
		fmt.Fprintf(&w.sb, "%s    d[\"%s\"] = self.%s.name\n", indent, f.Name, f.Name)
		fmt.Fprintf(&w.sb, "%selse:\n", indent)
		fmt.Fprintf(&w.sb, "%s    d[\"%s\"] = self.%s\n", indent, f.Name, f.Name)
	case f.Type.Kind == ir.KindStruct:
		if f.Type.Array.Kind == ir.RestArray || f.Type.Array.Kind == ir.CountRef {
			fmt.Fprintf(&w.sb, "%sd[\"%s\"] = [item._to_dict() for item in self.%s]\n", indent, f.Name, f.Name)
		} else {
			fmt.Fprintf(&w.sb, "%sd[\"%s\"] = self.%s._to_dict()\n", indent, f.Name, f.Name)
		}
	case f.Type.Kind == ir.KindEnum:
		fmt.Fprintf(&w.sb, "%sd[\"%s\"] = self.%s.name\n", indent, f.Name, f.Name)
	case f.Type.Primitive == ir.Bytes:
		fmt.Fprintf(&w.sb, "%sd[\"%s\"] = list(self.%s)\n", indent, f.Name, f.Name)
	case f.Type.Primitive == ir.String:
		if f.Type.Array.Kind == ir.FixedTerminator || f.Encoding != "" {
			fmt.Fprintf(&w.sb, "%sd[\"%s\"] = self.%s\n", indent, f.Name, f.Name)
		} else if f.Type.Array.Kind == ir.Terminator {
			fmt.Fprintf(&w.sb, "%sd[\"%s\"] = self.%s.decode(\"utf-8\", errors=\"replace\")\n", indent, f.Name, f.Name)
		} else {
			fmt.Fprintf(&w.sb, "%sd[\"%s\"] = self.%s.decode(\"utf-8\", errors=\"replace\") if isinstance(self.%s, bytes) else self.%s\n", indent, f.Name, f.Name, f.Name, f.Name)
		}
	default:
		fmt.Fprintf(&w.sb, "%sd[\"%s\"] = self.%s\n", indent, f.Name, f.Name)
	}
}

func (w *writer) writeToBytes(s *ir.Struct) {
	lengthSources, countSources := buildAutoComputeMap(s)

	fmt.Fprintf(&w.sb, "    def to_bytes(self) -> bytes:\n")
	fmt.Fprintf(&w.sb, "        _buf = bytearray()\n")

	for _, f := range s.Fields {
		endian := f.EffectiveEndian(s.Options.Endian)
		prefix := endianPrefix(endian)

		writeCode := w.captureFieldWrite(f, s, prefix, lengthSources, countSources)

		if f.Condition != nil {
			fmt.Fprintf(&w.sb, "        if self.%s is not None:\n", f.Name)
			w.sb.WriteString(indentLines(writeCode, "    "))
		} else {
			w.sb.WriteString(writeCode)
		}
	}

	fmt.Fprintf(&w.sb, "        return bytes(_buf)\n")
}

func (w *writer) captureFieldWrite(f *ir.Field, s *ir.Struct, prefix string, lengthSources, countSources map[string]string) string {
	var buf strings.Builder
	saved := w.sb
	w.sb = buf

	switch {
	case f.Type.Kind == ir.KindMatch:
		w.writeMatchWrite(f, s, prefix)
	case f.Type.Kind == ir.KindStruct:
		w.writeStructFieldWrite(f)
	case f.Type.Kind == ir.KindEnum:
		w.writeEnumFieldWrite(f, prefix, lengthSources, countSources)
	case f.Type.Kind == ir.KindPrimitive:
		w.writePrimitiveWrite(f, prefix, lengthSources, countSources)
	}

	result := w.sb.String()
	w.sb = saved
	return result
}

func (w *writer) writePrimitiveWrite(f *ir.Field, prefix string, lengthSources, countSources map[string]string) {
	prim := f.Type.Primitive

	valueExpr := fmt.Sprintf("self.%s", f.Name)
	if target, ok := lengthSources[f.Name]; ok {
		valueExpr = fmt.Sprintf("len(self.%s)", target)
	} else if target, ok := countSources[f.Name]; ok {
		valueExpr = fmt.Sprintf("len(self.%s)", target)
	}

	switch f.Type.Array.Kind {
	case ir.NotArray:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "        _buf += self.%s.encode(\"%s\")\n", f.Name, f.Encoding)
			} else {
				fmt.Fprintf(&w.sb, "        _buf += self.%s\n", f.Name)
			}
		} else {
			fmtStr := structFormat(prim)
			fmt.Fprintf(&w.sb, "        _buf += struct.pack(\"%s%s\", %s)\n", prefix, fmtStr, valueExpr)
		}

	case ir.FixedSize:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "        _buf += self.%s.encode(\"%s\")\n", f.Name, f.Encoding)
			} else {
				fmt.Fprintf(&w.sb, "        _buf += self.%s\n", f.Name)
			}
		} else {
			fmtStr := structFormat(prim)
			fmt.Fprintf(&w.sb, "        for _v in self.%s:\n", f.Name)
			fmt.Fprintf(&w.sb, "            _buf += struct.pack(\"%s%s\", _v)\n", prefix, fmtStr)
		}

	case ir.LengthRef:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "        _buf += self.%s.encode(\"%s\")\n", f.Name, f.Encoding)
			} else {
				fmt.Fprintf(&w.sb, "        _buf += self.%s\n", f.Name)
			}
		} else {
			fmtStr := structFormat(prim)
			fmt.Fprintf(&w.sb, "        for _v in self.%s:\n", f.Name)
			fmt.Fprintf(&w.sb, "            _buf += struct.pack(\"%s%s\", _v)\n", prefix, fmtStr)
		}

	case ir.RestArray:
		if prim == ir.Bytes || prim == ir.String {
			fmt.Fprintf(&w.sb, "        _buf += self.%s\n", f.Name)
		} else {
			fmtStr := structFormat(prim)
			fmt.Fprintf(&w.sb, "        for _v in self.%s:\n", f.Name)
			fmt.Fprintf(&w.sb, "            _buf += struct.pack(\"%s%s\", _v)\n", prefix, fmtStr)
		}

	case ir.Terminator:
		if prim == ir.Bytes || prim == ir.String {
			if f.Encoding != "" {
				fmt.Fprintf(&w.sb, "        _buf += self.%s.encode(\"%s\")\n", f.Name, f.Encoding)
			} else {
				fmt.Fprintf(&w.sb, "        _buf += self.%s\n", f.Name)
			}
			fmt.Fprintf(&w.sb, "        _buf += bytes([%d])\n", f.Type.Array.Sentinel)
		} else {
			fmtStr := structFormat(prim)
			fmt.Fprintf(&w.sb, "        for _v in self.%s:\n", f.Name)
			fmt.Fprintf(&w.sb, "            _buf += struct.pack(\"%s%s\", _v)\n", prefix, fmtStr)
			fmt.Fprintf(&w.sb, "        _buf += struct.pack(\"%s%s\", %d)\n", prefix, fmtStr, f.Type.Array.Sentinel)
		}

	case ir.FixedTerminator:
		enc := "utf-8"
		if f.Encoding != "" {
			enc = f.Encoding
		}
		fmt.Fprintf(&w.sb, "        _raw = self.%s.encode(\"%s\")\n", f.Name, enc)
		fmt.Fprintf(&w.sb, "        _buf += _raw + bytes([%d]) * (%d - len(_raw))\n", f.Type.Array.Sentinel, f.Type.Array.FixedSize)
	}
}

func (w *writer) writeMatchWrite(f *ir.Field, s *ir.Struct, prefix string) {
	m := f.Match
	for i, c := range m.Cases {
		if i == 0 {
			fmt.Fprintf(&w.sb, "        if self.%s == %d:\n", m.TagField, c.Value)
		} else {
			fmt.Fprintf(&w.sb, "        elif self.%s == %d:\n", m.TagField, c.Value)
		}
		w.writeTypeWrite(f.Name, &c.Type, prefix, "            ")
	}

	if m.Default != nil {
		w.sb.WriteString("        else:\n")
		w.writeTypeWrite(f.Name, m.Default, prefix, "            ")
	}
}

func (w *writer) writeTypeWrite(varName string, ft *ir.FieldType, prefix string, indent string) {
	switch ft.Kind {
	case ir.KindPrimitive:
		if ft.Primitive == ir.Bytes || ft.Primitive == ir.String {
			fmt.Fprintf(&w.sb, "%s_buf += self.%s\n", indent, varName)
		} else {
			fmtStr := structFormat(ft.Primitive)
			fmt.Fprintf(&w.sb, "%s_buf += struct.pack(\"%s%s\", self.%s)\n", indent, prefix, fmtStr, varName)
		}
	case ir.KindEnum:
		e := w.lookupEnum(ft.Ref)
		fmtStr := structFormat(e.BackingType)
		fmt.Fprintf(&w.sb, "%s_buf += struct.pack(\"%s%s\", int(self.%s))\n", indent, prefix, fmtStr, varName)
	case ir.KindStruct:
		fmt.Fprintf(&w.sb, "%s_buf += self.%s.to_bytes()\n", indent, varName)
	}
}

func (w *writer) writeStructFieldWrite(f *ir.Field) {
	switch f.Type.Array.Kind {
	case ir.RestArray, ir.CountRef:
		fmt.Fprintf(&w.sb, "        for _item in self.%s:\n", f.Name)
		fmt.Fprintf(&w.sb, "            _buf += _item.to_bytes()\n")
	default:
		fmt.Fprintf(&w.sb, "        _buf += self.%s.to_bytes()\n", f.Name)
	}
}

func (w *writer) writeEnumFieldWrite(f *ir.Field, prefix string, lengthSources, countSources map[string]string) {
	e := w.lookupEnum(f.Type.Ref)
	fmtStr := structFormat(e.BackingType)

	valueExpr := fmt.Sprintf("int(self.%s)", f.Name)
	if target, ok := lengthSources[f.Name]; ok {
		valueExpr = fmt.Sprintf("len(self.%s)", target)
	} else if target, ok := countSources[f.Name]; ok {
		valueExpr = fmt.Sprintf("len(self.%s)", target)
	}

	fmt.Fprintf(&w.sb, "        _buf += struct.pack(\"%s%s\", %s)\n", prefix, fmtStr, valueExpr)
}

func (w *writer) pythonType(f *ir.Field) string {
	base := w.basePythonType(f)
	if f.Condition != nil {
		return fmt.Sprintf("Optional[%s]", base)
	}
	return base
}

func (w *writer) basePythonType(f *ir.Field) string {
	switch f.Type.Kind {
	case ir.KindMatch:
		return w.matchPythonType(f.Match)
	case ir.KindStruct:
		if f.Type.Array.Kind == ir.RestArray || f.Type.Array.Kind == ir.CountRef {
			return fmt.Sprintf("list[\"%s\"]", f.Type.Ref)
		}
		return fmt.Sprintf("\"%s\"", f.Type.Ref)
	case ir.KindEnum:
		return fmt.Sprintf("\"%s\"", f.Type.Ref)
	case ir.KindPrimitive:
		return pythonPrimitiveType(f)
	}
	return "object"
}

func (w *writer) matchPythonType(m *ir.MatchSpec) string {
	seen := make(map[string]bool)
	var types []string

	addType := func(ft *ir.FieldType) {
		t := fieldTypePythonStr(ft)
		if !seen[t] {
			seen[t] = true
			types = append(types, t)
		}
	}

	for _, c := range m.Cases {
		addType(&c.Type)
	}
	if m.Default != nil {
		addType(m.Default)
	}

	if len(types) == 1 {
		return types[0]
	}
	return strings.Join(types, " | ")
}

func (w *writer) lookupEnum(name string) *ir.Enum {
	for _, e := range w.pkg.Enums {
		if e.Name == name {
			return e
		}
	}
	return nil
}

func emitPythonCall(expr *ir.ExprNode, thisName string) string {
	switch expr.FuncName {
	case "size":
		if expr.IsMember {
			return fmt.Sprintf("len(%s)", emitPythonExpr(expr.Operand, thisName))
		}
		if len(expr.Args) > 0 {
			return fmt.Sprintf("len(%s)", emitPythonExpr(expr.Args[0], thisName))
		}
	case "has":
		if !expr.IsMember && len(expr.Args) > 0 && expr.Args[0].Kind == ir.ExprSelect {
			sel := expr.Args[0]
			operand := emitPythonExpr(sel.Operand, thisName)
			return fmt.Sprintf("%s.%s is not None", operand, sel.Field)
		}
	case "startsWith":
		if expr.IsMember {
			operand := emitPythonExpr(expr.Operand, thisName)
			args := emitPythonArgs(expr.Args, thisName)
			return fmt.Sprintf("%s.startswith(%s)", operand, args)
		}
	case "endsWith":
		if expr.IsMember {
			operand := emitPythonExpr(expr.Operand, thisName)
			args := emitPythonArgs(expr.Args, thisName)
			return fmt.Sprintf("%s.endswith(%s)", operand, args)
		}
	case "contains":
		if expr.IsMember && len(expr.Args) > 0 {
			operand := emitPythonExpr(expr.Operand, thisName)
			arg := emitPythonExpr(expr.Args[0], thisName)
			return fmt.Sprintf("%s in %s", arg, operand)
		}
	case "matches":
		if expr.IsMember && len(expr.Args) > 0 {
			operand := emitPythonExpr(expr.Operand, thisName)
			arg := emitPythonExpr(expr.Args[0], thisName)
			return fmt.Sprintf("re.search(%s, %s) is not None", arg, operand)
		}
	}

	if expr.IsMember {
		operand := emitPythonExpr(expr.Operand, thisName)
		args := emitPythonArgs(expr.Args, thisName)
		return fmt.Sprintf("%s.%s(%s)", operand, expr.FuncName, args)
	}
	args := emitPythonArgs(expr.Args, thisName)
	return fmt.Sprintf("%s(%s)", expr.FuncName, args)
}

func emitPythonExpr(expr *ir.ExprNode, thisName string) string {
	switch expr.Kind {
	case ir.ExprLiteral:
		lit := expr.Literal
		switch {
		case lit.Int != nil:
			return fmt.Sprintf("%d", *lit.Int)
		case lit.Bool != nil:
			if *lit.Bool {
				return "True"
			}
			return "False"
		case lit.Str != nil:
			return fmt.Sprintf("%q", *lit.Str)
		case lit.Float != nil:
			return fmt.Sprintf("%g", *lit.Float)
		}
	case ir.ExprIdent:
		if expr.Ident == "this" {
			return thisName
		}
		return expr.Ident
	case ir.ExprBinary:
		left := emitPythonExpr(expr.Left, thisName)
		right := emitPythonExpr(expr.Right, thisName)
		op := expr.Op
		switch op {
		case "&&":
			op = "and"
		case "||":
			op = "or"
		}
		return fmt.Sprintf("(%s %s %s)", left, op, right)
	case ir.ExprUnary:
		operand := emitPythonExpr(expr.Operand, thisName)
		if expr.Op == "!" {
			return fmt.Sprintf("(not (%s))", operand)
		}
		return fmt.Sprintf("(%s(%s))", expr.Op, operand)
	case ir.ExprSelect:
		operand := emitPythonExpr(expr.Operand, thisName)
		return fmt.Sprintf("%s.%s", operand, expr.Field)
	case ir.ExprCall:
		return emitPythonCall(expr, thisName)
	}
	return "None"
}

func buildAutoComputeMap(s *ir.Struct) (lengthSources, countSources map[string]string) {
	lengthSources = make(map[string]string)
	countSources = make(map[string]string)
	for _, f := range s.Fields {
		if f.Type.Array.Kind == ir.LengthRef {
			lengthSources[f.Type.Array.LengthRef] = f.Name
		}
		if f.Type.Array.Kind == ir.CountRef && !strings.Contains(f.Type.Array.CountRef, ".") {
			countSources[f.Type.Array.CountRef] = f.Name
		}
	}
	return
}

func pythonPrimitiveType(f *ir.Field) string {
	prim := f.Type.Primitive
	isArray := f.Type.Array.Kind != ir.NotArray

	switch prim {
	case ir.Bytes, ir.String:
		if f.Type.Array.Kind == ir.FixedTerminator || f.Encoding != "" {
			return "str"
		}
		return "bytes"
	case ir.F32, ir.F64:
		if isArray {
			return "list[float]"
		}
		return "float"
	default:
		if isArray {
			return "list[int]"
		}
		return "int"
	}
}

func fieldTypePythonStr(ft *ir.FieldType) string {
	switch ft.Kind {
	case ir.KindStruct:
		return fmt.Sprintf("\"%s\"", ft.Ref)
	case ir.KindEnum:
		return fmt.Sprintf("\"%s\"", ft.Ref)
	case ir.KindPrimitive:
		switch ft.Primitive {
		case ir.Bytes, ir.String:
			return "bytes"
		case ir.F32, ir.F64:
			return "float"
		default:
			return "int"
		}
	}
	return "object"
}

func indentLines(code string, extra string) string {
	lines := strings.Split(code, "\n")
	var result strings.Builder
	for _, line := range lines {
		if line == "" {
			continue
		}
		result.WriteString(extra)
		result.WriteString(line)
		result.WriteByte('\n')
	}
	return result.String()
}

func emitPythonArgs(args []*ir.ExprNode, thisName string) string {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = emitPythonExpr(a, thisName)
	}
	return strings.Join(parts, ", ")
}

func structFormat(prim ir.PrimitiveType) string {
	switch prim {
	case ir.U8:
		return "B"
	case ir.I8:
		return "b"
	case ir.U16:
		return "H"
	case ir.I16:
		return "h"
	case ir.U32:
		return "I"
	case ir.I32:
		return "i"
	case ir.U64:
		return "Q"
	case ir.I64:
		return "q"
	case ir.F32:
		return "f"
	case ir.F64:
		return "d"
	default:
		return "B"
	}
}

func endianPrefix(e ir.Endian) string {
	if e == ir.BigEndian {
		return ">"
	}
	return "<"
}
