// Generated by cleave. Do not edit.
// Package: validation
// Cargo dependencies: none.

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    UnexpectedEof {
        offset: usize,
        needed: usize,
        remaining: usize,
    },
    InvalidEnum {
        enum_name: &'static str,
        value: i128,
    },
    UnknownTag {
        struct_name: &'static str,
        field: &'static str,
        value: i128,
    },
    Validation {
        id: &'static str,
        message: &'static str,
        field: &'static str,
    },
    UnsupportedEncoding {
        encoding: &'static str,
    },
    InvalidEncoding {
        encoding: &'static str,
    },
    InvalidRegex {
        pattern: ::std::string::String,
        message: ::std::string::String,
    },
    InvalidLength {
        field: &'static str,
        value: i128,
    },
    LengthOverflow {
        field: &'static str,
        value: ::std::string::String,
        target: &'static str,
    },
    FixedSize {
        field: &'static str,
        expected: usize,
        actual: usize,
    },
    MatchType {
        field: &'static str,
        tag: i128,
    },
    NoProgress {
        field: &'static str,
        offset: usize,
    },
}

impl ::std::fmt::Display for Error {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Self::UnexpectedEof {
                offset,
                needed,
                remaining,
            } => write!(
                formatter,
                "unexpected end of input at offset {offset}: need {needed} bytes, have {remaining}",
            ),
            Self::InvalidEnum { enum_name, value } => {
                write!(formatter, "invalid {enum_name} value {value}")
            }
            Self::UnknownTag {
                struct_name,
                field,
                value,
            } => {
                write!(formatter, "unknown tag {value} for {struct_name}.{field}")
            }
            Self::Validation { id, message, field } => {
                write!(formatter, "validation {id} failed for {field}: {message}")
            }
            Self::UnsupportedEncoding { encoding } => {
                write!(formatter, "unsupported encoding {encoding}")
            }
            Self::InvalidEncoding { encoding } => {
                write!(formatter, "invalid {encoding} text")
            }
            Self::InvalidRegex { pattern, message } => {
                write!(
                    formatter,
                    "invalid regular expression {pattern:?}: {message}"
                )
            }
            Self::InvalidLength { field, value } => {
                write!(formatter, "invalid length {value} for {field}")
            }
            Self::LengthOverflow {
                field,
                value,
                target,
            } => {
                write!(
                    formatter,
                    "length {value} for {field} does not fit {target}"
                )
            }
            Self::FixedSize {
                field,
                expected,
                actual,
            } => write!(
                formatter,
                "{field} has length {actual}, expected {expected}",
            ),
            Self::MatchType { field, tag } => {
                write!(formatter, "payload for {field} does not match tag {tag}")
            }
            Self::NoProgress { field, offset } => {
                write!(
                    formatter,
                    "parsing {field} made no progress at offset {offset}"
                )
            }
        }
    }
}

impl ::std::error::Error for Error {}

#[allow(dead_code, reason = "some schemas do not read byte slices directly")]
fn take<'a>(
    buf: &'a [u8],
    offset: &mut usize,
    length: usize,
) -> ::std::result::Result<&'a [u8], Error> {
    let start = *offset;
    let end = start
        .checked_add(length)
        .ok_or_else(|| Error::LengthOverflow {
            field: "offset",
            value: length.to_string(),
            target: "usize",
        })?;
    let remaining = buf.len().saturating_sub(start);
    let bytes = buf.get(start..end).ok_or(Error::UnexpectedEof {
        offset: start,
        needed: length,
        remaining,
    })?;
    *offset = end;
    Ok(bytes)
}

#[allow(dead_code, reason = "some schemas do not contain numeric fields")]
fn read_array<const N: usize>(
    buf: &[u8],
    offset: &mut usize,
) -> ::std::result::Result<[u8; N], Error> {
    let bytes = take(buf, offset, N)?;
    <[u8; N]>::try_from(bytes).map_err(|_| Error::FixedSize {
        field: "primitive",
        expected: N,
        actual: bytes.len(),
    })
}

fn decode_text(
    bytes: &[u8],
    encoding: &'static str,
) -> ::std::result::Result<::std::string::String, Error> {
    if encoding.eq_ignore_ascii_case("utf-8") || encoding.eq_ignore_ascii_case("utf8") {
        return ::std::str::from_utf8(bytes)
            .map(::std::primitive::str::to_owned)
            .map_err(|_| Error::InvalidEncoding { encoding });
    }
    Err(Error::UnsupportedEncoding { encoding })
}

fn encode_text(
    value: &str,
    encoding: &'static str,
) -> ::std::result::Result<::std::vec::Vec<u8>, Error> {
    if encoding.eq_ignore_ascii_case("utf-8") || encoding.eq_ignore_ascii_case("utf8") {
        return Ok(value.as_bytes().to_vec());
    }
    Err(Error::UnsupportedEncoding { encoding })
}

#[allow(dead_code, reason = "empty schemas have no JSON strings to write")]
fn write_json_string(json: &mut ::std::string::String, value: &str) {
    json.push('"');
    for character in value.chars() {
        match character {
            '"' => json.push_str("\\\""),
            '\\' => json.push_str("\\\\"),
            '\u{0008}' => json.push_str("\\b"),
            '\u{000c}' => json.push_str("\\f"),
            '\n' => json.push_str("\\n"),
            '\r' => json.push_str("\\r"),
            '\t' => json.push_str("\\t"),
            control if control <= '\u{001f}' => {
                json.push_str("\\u");
                let code = u32::from(control);
                for shift in [12_u32, 8, 4, 0] {
                    if let ::std::option::Option::Some(digit) =
                        ::std::char::from_digit((code >> shift) & 0x0f, 16)
                    {
                        json.push(digit);
                    }
                }
            }
            other => json.push(other),
        }
    }
    json.push('"');
}

#[allow(non_camel_case_types, reason = "schema names are preserved")]
#[allow(non_snake_case, reason = "schema field names are preserved")]
#[derive(Debug, Clone, PartialEq)]
pub struct Header {
    pub magic: u32,
    pub version: u16,
    pub flags: u8,
}

impl Header {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn parse(buf: &[u8], offset: &mut usize) -> ::std::result::Result<Self, Error> {
        let magic = u32::from_be_bytes(self::read_array::<4>(buf, offset)?);
        #[allow(
            clippy::absurd_extreme_comparisons,
            clippy::float_cmp,
            clippy::manual_range_contains,
            clippy::nonminimal_bool,
            unused_comparisons,
            reason = "validation expressions preserve schema comparisons"
        )]
        if !(magic == 1_129_070_934) {
            return Err(Error::Validation {
                id: "magic.check",
                message: "invalid magic number",
                field: "magic",
            });
        }
        let version = u16::from_be_bytes(self::read_array::<2>(buf, offset)?);
        #[allow(
            clippy::absurd_extreme_comparisons,
            clippy::float_cmp,
            clippy::manual_range_contains,
            clippy::nonminimal_bool,
            unused_comparisons,
            reason = "validation expressions preserve schema comparisons"
        )]
        if !(version >= 1) {
            return Err(Error::Validation {
                id: "version.min",
                message: "version must be at least 1",
                field: "version",
            });
        }
        #[allow(
            clippy::absurd_extreme_comparisons,
            clippy::float_cmp,
            clippy::manual_range_contains,
            clippy::nonminimal_bool,
            unused_comparisons,
            reason = "validation expressions preserve schema comparisons"
        )]
        if !(version <= 100) {
            return Err(Error::Validation {
                id: "version.max",
                message: "version must be at most 100",
                field: "version",
            });
        }
        let flags = u8::from_ne_bytes(self::read_array::<1>(buf, offset)?);
        #[allow(
            clippy::absurd_extreme_comparisons,
            clippy::float_cmp,
            clippy::manual_range_contains,
            clippy::nonminimal_bool,
            unused_comparisons,
            reason = "validation expressions preserve schema comparisons"
        )]
        if !((flags >= 0) && (flags <= 7)) {
            return Err(Error::Validation {
                id: "flags.range",
                message: "flags must be between 0 and 7",
                field: "flags",
            });
        }
        Ok(Self {
            magic,
            version,
            flags,
        })
    }
}

impl Header {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, Error> {
        let mut buf = ::std::vec::Vec::new();
        let value = &self.magic;
        buf.extend_from_slice(&(*value).to_be_bytes());
        let value = &self.version;
        buf.extend_from_slice(&(*value).to_be_bytes());
        let value = &self.flags;
        buf.extend_from_slice(&(*value).to_ne_bytes());
        Ok(buf)
    }
}

impl Header {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_json(&self) -> ::std::string::String {
        let mut json = ::std::string::String::from("{");
        write_json_string(&mut json, "magic");
        json.push(':');
        let value = &self.magic;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "version");
        json.push(':');
        let value = &self.version;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "flags");
        json.push(':');
        let value = &self.flags;
        json.push_str(&value.to_string());
        json.push('}');
        json
    }
}

#[allow(non_camel_case_types, reason = "schema names are preserved")]
#[allow(non_snake_case, reason = "schema field names are preserved")]
#[derive(Debug, Clone, PartialEq)]
pub struct Record {
    pub name: ::std::string::String,
    pub priority: u8,
    pub has_data: u8,
    pub data: ::std::option::Option<u32>,
}

impl Record {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn parse(buf: &[u8], offset: &mut usize) -> ::std::result::Result<Self, Error> {
        let name = {
            let bytes = self::take(buf, offset, 64)?;
            let end = bytes
                .iter()
                .position(|byte| *byte == 0)
                .unwrap_or(bytes.len());
            let text = bytes.get(..end).ok_or(Error::UnexpectedEof {
                offset: *offset,
                needed: end,
                remaining: bytes.len(),
            })?;
            self::decode_text(text, "utf-8")?
        };
        let priority = u8::from_ne_bytes(self::read_array::<1>(buf, offset)?);
        #[allow(
            clippy::absurd_extreme_comparisons,
            clippy::float_cmp,
            clippy::manual_range_contains,
            clippy::nonminimal_bool,
            unused_comparisons,
            reason = "validation expressions preserve schema comparisons"
        )]
        if !((priority >= 1) && (priority <= 3)) {
            return Err(Error::Validation {
                id: "priority.valid",
                message: "priority must be low (1), medium (2), or high (3)",
                field: "priority",
            });
        }
        let has_data = u8::from_ne_bytes(self::read_array::<1>(buf, offset)?);
        let data = if has_data != 0 {
            let parsed = u32::from_le_bytes(self::read_array::<4>(buf, offset)?);
            ::std::option::Option::Some(parsed)
        } else {
            ::std::option::Option::None
        };
        Ok(Self {
            name,
            priority,
            has_data,
            data,
        })
    }
}

impl Record {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, Error> {
        let mut buf = ::std::vec::Vec::new();
        let value = &self.name;
        let bytes = encode_text(value.as_str(), "utf-8")?;
        if bytes.len() > 64 {
            return Err(Error::FixedSize {
                field: "name",
                expected: 64,
                actual: bytes.len(),
            });
        }
        buf.extend_from_slice(&bytes);
        let padding = 64 - bytes.len();
        let new_len = buf
            .len()
            .checked_add(padding)
            .ok_or_else(|| Error::LengthOverflow {
                field: "name",
                value: padding.to_string(),
                target: "usize",
            })?;
        buf.resize(new_len, 0_u8);
        let value = &self.priority;
        buf.extend_from_slice(&(*value).to_ne_bytes());
        let value = &self.has_data;
        buf.extend_from_slice(&(*value).to_ne_bytes());
        if let ::std::option::Option::Some(value) = &self.data {
            buf.extend_from_slice(&(*value).to_le_bytes());
        }
        Ok(buf)
    }
}

impl Record {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_json(&self) -> ::std::string::String {
        let mut json = ::std::string::String::from("{");
        write_json_string(&mut json, "name");
        json.push(':');
        let value = &self.name;
        write_json_string(&mut json, value);
        json.push(',');
        write_json_string(&mut json, "priority");
        json.push(':');
        let value = &self.priority;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "has_data");
        json.push(':');
        let value = &self.has_data;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "data");
        json.push(':');
        if let ::std::option::Option::Some(value) = &self.data {
            json.push_str(&value.to_string());
        } else {
            json.push_str("null");
        }
        json.push('}');
        json
    }
}

#[allow(non_camel_case_types, reason = "schema names are preserved")]
#[allow(non_snake_case, reason = "schema field names are preserved")]
#[derive(Debug, Clone, PartialEq)]
pub struct Container {
    pub header: Header,
    pub record_count: u32,
    pub records: ::std::vec::Vec<Record>,
}

impl Container {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn parse(buf: &[u8], offset: &mut usize) -> ::std::result::Result<Self, Error> {
        let header = Header::parse(buf, offset)?;
        let record_count = u32::from_be_bytes(self::read_array::<4>(buf, offset)?);
        let records = {
            let raw_count = record_count;
            #[allow(
                clippy::unnecessary_fallible_conversions,
                reason = "length fields can use signed or wide integer types"
            )]
            let count = usize::try_from(raw_count).map_err(|_| Error::InvalidLength {
                field: "records",
                value: i128::from(raw_count),
            })?;
            let mut values = ::std::vec::Vec::with_capacity(count);
            for _ in 0..count {
                values.push(Record::parse(buf, offset)?);
            }
            values
        };
        Ok(Self {
            header,
            record_count,
            records,
        })
    }
}

impl Container {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, Error> {
        let mut buf = ::std::vec::Vec::new();
        let value = &self.header;
        buf.extend_from_slice(&value.to_bytes()?);
        let actual = self.records.len();
        let computed = u32::try_from(actual).map_err(|_| Error::LengthOverflow {
            field: "record_count",
            value: actual.to_string(),
            target: "u32",
        })?;
        buf.extend_from_slice(&(computed).to_be_bytes());
        let value = &self.records;
        for item in value {
            buf.extend_from_slice(&item.to_bytes()?);
        }
        Ok(buf)
    }
}

impl Container {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_json(&self) -> ::std::string::String {
        let mut json = ::std::string::String::from("{");
        write_json_string(&mut json, "header");
        json.push(':');
        let value = &self.header;
        json.push_str(&value.to_json());
        json.push(',');
        write_json_string(&mut json, "record_count");
        json.push(':');
        let value = &self.record_count;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "records");
        json.push(':');
        let value = &self.records;
        json.push('[');
        for (index, item) in value.iter().enumerate() {
            if index > 0 {
                json.push(',');
            }
            let value = item;
            json.push_str(&value.to_json());
        }
        json.push(']');
        json.push('}');
        json
    }
}
