// Generated by cleave. Do not edit.
// Package: png
// Cargo dependencies: none.

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    UnexpectedEof {
        offset: usize,
        needed: usize,
        remaining: usize,
    },
    InvalidEnum {
        enum_name: &'static str,
        value: i128,
    },
    UnknownTag {
        struct_name: &'static str,
        field: &'static str,
        value: i128,
    },
    Validation {
        id: &'static str,
        message: &'static str,
        field: &'static str,
    },
    UnsupportedEncoding {
        encoding: &'static str,
    },
    InvalidEncoding {
        encoding: &'static str,
    },
    InvalidRegex {
        pattern: ::std::string::String,
        message: ::std::string::String,
    },
    InvalidLength {
        field: &'static str,
        value: i128,
    },
    LengthOverflow {
        field: &'static str,
        value: ::std::string::String,
        target: &'static str,
    },
    FixedSize {
        field: &'static str,
        expected: usize,
        actual: usize,
    },
    MatchType {
        field: &'static str,
        tag: i128,
    },
    NoProgress {
        field: &'static str,
        offset: usize,
    },
}

impl ::std::fmt::Display for Error {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Self::UnexpectedEof {
                offset,
                needed,
                remaining,
            } => write!(
                formatter,
                "unexpected end of input at offset {offset}: need {needed} bytes, have {remaining}",
            ),
            Self::InvalidEnum { enum_name, value } => {
                write!(formatter, "invalid {enum_name} value {value}")
            }
            Self::UnknownTag {
                struct_name,
                field,
                value,
            } => {
                write!(formatter, "unknown tag {value} for {struct_name}.{field}")
            }
            Self::Validation { id, message, field } => {
                write!(formatter, "validation {id} failed for {field}: {message}")
            }
            Self::UnsupportedEncoding { encoding } => {
                write!(formatter, "unsupported encoding {encoding}")
            }
            Self::InvalidEncoding { encoding } => {
                write!(formatter, "invalid {encoding} text")
            }
            Self::InvalidRegex { pattern, message } => {
                write!(
                    formatter,
                    "invalid regular expression {pattern:?}: {message}"
                )
            }
            Self::InvalidLength { field, value } => {
                write!(formatter, "invalid length {value} for {field}")
            }
            Self::LengthOverflow {
                field,
                value,
                target,
            } => {
                write!(
                    formatter,
                    "length {value} for {field} does not fit {target}"
                )
            }
            Self::FixedSize {
                field,
                expected,
                actual,
            } => write!(
                formatter,
                "{field} has length {actual}, expected {expected}",
            ),
            Self::MatchType { field, tag } => {
                write!(formatter, "payload for {field} does not match tag {tag}")
            }
            Self::NoProgress { field, offset } => {
                write!(
                    formatter,
                    "parsing {field} made no progress at offset {offset}"
                )
            }
        }
    }
}

impl ::std::error::Error for Error {}

#[allow(dead_code, reason = "some schemas do not read byte slices directly")]
fn take<'a>(
    buf: &'a [u8],
    offset: &mut usize,
    length: usize,
) -> ::std::result::Result<&'a [u8], Error> {
    let start = *offset;
    let end = start
        .checked_add(length)
        .ok_or_else(|| Error::LengthOverflow {
            field: "offset",
            value: length.to_string(),
            target: "usize",
        })?;
    let remaining = buf.len().saturating_sub(start);
    let bytes = buf.get(start..end).ok_or(Error::UnexpectedEof {
        offset: start,
        needed: length,
        remaining,
    })?;
    *offset = end;
    Ok(bytes)
}

#[allow(dead_code, reason = "some schemas do not contain numeric fields")]
fn read_array<const N: usize>(
    buf: &[u8],
    offset: &mut usize,
) -> ::std::result::Result<[u8; N], Error> {
    let bytes = take(buf, offset, N)?;
    <[u8; N]>::try_from(bytes).map_err(|_| Error::FixedSize {
        field: "primitive",
        expected: N,
        actual: bytes.len(),
    })
}

#[allow(dead_code, reason = "empty schemas have no JSON strings to write")]
fn write_json_string(json: &mut ::std::string::String, value: &str) {
    json.push('"');
    for character in value.chars() {
        match character {
            '"' => json.push_str("\\\""),
            '\\' => json.push_str("\\\\"),
            '\u{0008}' => json.push_str("\\b"),
            '\u{000c}' => json.push_str("\\f"),
            '\n' => json.push_str("\\n"),
            '\r' => json.push_str("\\r"),
            '\t' => json.push_str("\\t"),
            control if control <= '\u{001f}' => {
                json.push_str("\\u");
                let code = u32::from(control);
                for shift in [12_u32, 8, 4, 0] {
                    if let ::std::option::Option::Some(digit) =
                        ::std::char::from_digit((code >> shift) & 0x0f, 16)
                    {
                        json.push(digit);
                    }
                }
            }
            other => json.push(other),
        }
    }
    json.push('"');
}

#[allow(non_camel_case_types, reason = "schema names are preserved")]
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColorType {
    Grayscale = 0,
    RGB = 2,
    Palette = 3,
    GrayscaleAlpha = 4,
    RGBA = 6,
}

impl ::std::convert::TryFrom<u8> for ColorType {
    type Error = Error;

    fn try_from(value: u8) -> ::std::result::Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Grayscale),
            2 => Ok(Self::RGB),
            3 => Ok(Self::Palette),
            4 => Ok(Self::GrayscaleAlpha),
            6 => Ok(Self::RGBA),
            _ => Err(Error::InvalidEnum {
                enum_name: "ColorType",
                value: i128::from(value),
            }),
        }
    }
}

impl ::std::convert::From<ColorType> for u8 {
    fn from(value: ColorType) -> Self {
        value as u8
    }
}

#[allow(non_camel_case_types, reason = "schema names are preserved")]
#[allow(non_snake_case, reason = "schema field names are preserved")]
#[derive(Debug, Clone, PartialEq)]
pub struct Header {
    pub signature: [u8; 8],
}

impl Header {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn parse(buf: &[u8], offset: &mut usize) -> ::std::result::Result<Self, Error> {
        let signature = {
            let bytes = self::take(buf, offset, 8)?;
            <[u8; 8]>::try_from(bytes).map_err(|_| Error::FixedSize {
                field: "signature",
                expected: 8,
                actual: bytes.len(),
            })?
        };
        Ok(Self { signature })
    }
}

impl Header {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, Error> {
        let mut buf = ::std::vec::Vec::new();
        let value = &self.signature;
        buf.extend_from_slice(value);
        Ok(buf)
    }
}

impl Header {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_json(&self) -> ::std::string::String {
        let mut json = ::std::string::String::from("{");
        write_json_string(&mut json, "signature");
        json.push(':');
        let value = &self.signature;
        json.push('[');
        for (index, item) in value.iter().enumerate() {
            if index > 0 {
                json.push(',');
            }
            let value = item;
            json.push_str(&value.to_string());
        }
        json.push(']');
        json.push('}');
        json
    }
}

#[allow(non_camel_case_types, reason = "schema names are preserved")]
#[allow(non_snake_case, reason = "schema field names are preserved")]
#[derive(Debug, Clone, PartialEq)]
pub struct IHDRData {
    pub width: u32,
    pub height: u32,
    pub bit_depth: u8,
    pub color_type: ColorType,
    pub compression: u8,
    pub filter: u8,
    pub interlace: u8,
}

impl IHDRData {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn parse(buf: &[u8], offset: &mut usize) -> ::std::result::Result<Self, Error> {
        let width = u32::from_be_bytes(self::read_array::<4>(buf, offset)?);
        let height = u32::from_be_bytes(self::read_array::<4>(buf, offset)?);
        let bit_depth = u8::from_ne_bytes(self::read_array::<1>(buf, offset)?);
        let color_type =
            ColorType::try_from(u8::from_ne_bytes(self::read_array::<1>(buf, offset)?))?;
        let compression = u8::from_ne_bytes(self::read_array::<1>(buf, offset)?);
        let filter = u8::from_ne_bytes(self::read_array::<1>(buf, offset)?);
        let interlace = u8::from_ne_bytes(self::read_array::<1>(buf, offset)?);
        Ok(Self {
            width,
            height,
            bit_depth,
            color_type,
            compression,
            filter,
            interlace,
        })
    }
}

impl IHDRData {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, Error> {
        let mut buf = ::std::vec::Vec::new();
        let value = &self.width;
        buf.extend_from_slice(&(*value).to_be_bytes());
        let value = &self.height;
        buf.extend_from_slice(&(*value).to_be_bytes());
        let value = &self.bit_depth;
        buf.extend_from_slice(&(*value).to_ne_bytes());
        let value = &self.color_type;
        let raw: u8 = (*value).into();
        buf.extend_from_slice(&(raw).to_ne_bytes());
        let value = &self.compression;
        buf.extend_from_slice(&(*value).to_ne_bytes());
        let value = &self.filter;
        buf.extend_from_slice(&(*value).to_ne_bytes());
        let value = &self.interlace;
        buf.extend_from_slice(&(*value).to_ne_bytes());
        Ok(buf)
    }
}

impl IHDRData {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_json(&self) -> ::std::string::String {
        let mut json = ::std::string::String::from("{");
        write_json_string(&mut json, "width");
        json.push(':');
        let value = &self.width;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "height");
        json.push(':');
        let value = &self.height;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "bit_depth");
        json.push(':');
        let value = &self.bit_depth;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "color_type");
        json.push(':');
        let value = &self.color_type;
        let raw: u8 = (*value).into();
        json.push_str(&raw.to_string());
        json.push(',');
        write_json_string(&mut json, "compression");
        json.push(':');
        let value = &self.compression;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "filter");
        json.push(':');
        let value = &self.filter;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "interlace");
        json.push(':');
        let value = &self.interlace;
        json.push_str(&value.to_string());
        json.push('}');
        json
    }
}

#[allow(non_camel_case_types, reason = "schema names are preserved")]
#[allow(non_snake_case, reason = "schema field names are preserved")]
#[derive(Debug, Clone, PartialEq)]
pub struct Chunk {
    pub length: u32,
    pub r#type: [u8; 4],
    pub data: ::std::vec::Vec<u8>,
    pub crc: u32,
}

impl Chunk {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn parse(buf: &[u8], offset: &mut usize) -> ::std::result::Result<Self, Error> {
        let length = u32::from_be_bytes(self::read_array::<4>(buf, offset)?);
        let r#type = {
            let bytes = self::take(buf, offset, 4)?;
            <[u8; 4]>::try_from(bytes).map_err(|_| Error::FixedSize {
                field: "type",
                expected: 4,
                actual: bytes.len(),
            })?
        };
        let data = {
            let raw_count = length;
            #[allow(
                clippy::unnecessary_fallible_conversions,
                reason = "length fields can use signed or wide integer types"
            )]
            let count = usize::try_from(raw_count).map_err(|_| Error::InvalidLength {
                field: "data",
                value: i128::from(raw_count),
            })?;
            self::take(buf, offset, count)?.to_vec()
        };
        let crc = u32::from_be_bytes(self::read_array::<4>(buf, offset)?);
        Ok(Self {
            length,
            r#type,
            data,
            crc,
        })
    }
}

impl Chunk {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, Error> {
        let mut buf = ::std::vec::Vec::new();
        let actual = self.data.len();
        let computed = u32::try_from(actual).map_err(|_| Error::LengthOverflow {
            field: "length",
            value: actual.to_string(),
            target: "u32",
        })?;
        buf.extend_from_slice(&(computed).to_be_bytes());
        let value = &self.r#type;
        buf.extend_from_slice(value);
        let value = &self.data;
        buf.extend_from_slice(value);
        let value = &self.crc;
        buf.extend_from_slice(&(*value).to_be_bytes());
        Ok(buf)
    }
}

impl Chunk {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_json(&self) -> ::std::string::String {
        let mut json = ::std::string::String::from("{");
        write_json_string(&mut json, "length");
        json.push(':');
        let value = &self.length;
        json.push_str(&value.to_string());
        json.push(',');
        write_json_string(&mut json, "type");
        json.push(':');
        let value = &self.r#type;
        json.push('[');
        for (index, item) in value.iter().enumerate() {
            if index > 0 {
                json.push(',');
            }
            let value = item;
            json.push_str(&value.to_string());
        }
        json.push(']');
        json.push(',');
        write_json_string(&mut json, "data");
        json.push(':');
        let value = &self.data;
        json.push('[');
        for (index, item) in value.iter().enumerate() {
            if index > 0 {
                json.push(',');
            }
            let value = item;
            json.push_str(&value.to_string());
        }
        json.push(']');
        json.push(',');
        write_json_string(&mut json, "crc");
        json.push(':');
        let value = &self.crc;
        json.push_str(&value.to_string());
        json.push('}');
        json
    }
}

#[allow(non_camel_case_types, reason = "schema names are preserved")]
#[allow(non_snake_case, reason = "schema field names are preserved")]
#[derive(Debug, Clone, PartialEq)]
pub struct PngFile {
    pub header: Header,
    pub chunks: ::std::vec::Vec<Chunk>,
}

impl PngFile {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn parse(buf: &[u8], offset: &mut usize) -> ::std::result::Result<Self, Error> {
        let header = Header::parse(buf, offset)?;
        let chunks = {
            let mut values = ::std::vec::Vec::new();
            while *offset < buf.len() {
                let previous = *offset;
                let value = Chunk::parse(buf, offset)?;
                if *offset == previous {
                    return Err(Error::NoProgress {
                        field: "chunks",
                        offset: previous,
                    });
                }
                values.push(value);
            }
            values
        };
        Ok(Self { header, chunks })
    }
}

impl PngFile {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, Error> {
        let mut buf = ::std::vec::Vec::new();
        let value = &self.header;
        buf.extend_from_slice(&value.to_bytes()?);
        let value = &self.chunks;
        for item in value {
            buf.extend_from_slice(&item.to_bytes()?);
        }
        Ok(buf)
    }
}

impl PngFile {
    #[allow(non_snake_case, reason = "schema field names are preserved")]
    #[allow(clippy::too_many_lines, reason = "schema methods follow field order")]
    pub fn to_json(&self) -> ::std::string::String {
        let mut json = ::std::string::String::from("{");
        write_json_string(&mut json, "header");
        json.push(':');
        let value = &self.header;
        json.push_str(&value.to_json());
        json.push(',');
        write_json_string(&mut json, "chunks");
        json.push(':');
        let value = &self.chunks;
        json.push('[');
        for (index, item) in value.iter().enumerate() {
            if index > 0 {
                json.push(',');
            }
            let value = item;
            json.push_str(&value.to_json());
        }
        json.push(']');
        json.push('}');
        json
    }
}
