// Generated by cleave. Do not edit.
#include "png.h"

namespace png {

namespace {

template <typename T>
T swap32(T val) {
    uint32_t v;
    std::memcpy(&v, &val, sizeof(v));
    v = ((v >> 24) & 0xFF) | ((v >> 8) & 0xFF00) | ((v << 8) & 0xFF0000) | ((v << 24) & 0xFF000000);
    T out;
    std::memcpy(&out, &v, sizeof(out));
    return out;
}

} // namespace

Header Header::parse(const uint8_t* buf, size_t len, size_t& offset) {
    Header result;
    if (offset + 8 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.signature, buf + offset, 8);
    offset += 8;
    return result;
}

std::string Header::to_json() const {
    std::string s = "{";
    s += "\"signature\":";
    s += "[";
    for (size_t i = 0; i < 8; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(signature[i]);
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> Header::to_bytes() const {
    std::vector<uint8_t> _buf;
    _buf.insert(_buf.end(), signature, signature + 8);
    return _buf;
}

IHDRData IHDRData::parse(const uint8_t* buf, size_t len, size_t& offset) {
    IHDRData result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.width, buf + offset, 4);
    result.width = swap32(result.width);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.height, buf + offset, 4);
    result.height = swap32(result.height);
    offset += 4;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.bit_depth = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    uint8_t color_type = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    result.color_type = static_cast<ColorType>(color_type);
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.compression = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.filter = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.interlace = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    return result;
}

std::string IHDRData::to_json() const {
    std::string s = "{";
    s += "\"width\":";
    s += std::to_string(width);
    s += ",";
    s += "\"height\":";
    s += std::to_string(height);
    s += ",";
    s += "\"bit_depth\":";
    s += std::to_string(bit_depth);
    s += ",";
    s += "\"color_type\":";
    s += std::to_string(static_cast<int>(color_type));
    s += ",";
    s += "\"compression\":";
    s += std::to_string(compression);
    s += ",";
    s += "\"filter\":";
    s += std::to_string(filter);
    s += ",";
    s += "\"interlace\":";
    s += std::to_string(interlace);
    s += "}";
    return s;
}

std::vector<uint8_t> IHDRData::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = swap32(width);
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = swap32(height);
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.push_back(static_cast<uint8_t>(bit_depth));
    _buf.push_back(static_cast<uint8_t>(static_cast<uint8_t>(color_type)));
    _buf.push_back(static_cast<uint8_t>(compression));
    _buf.push_back(static_cast<uint8_t>(filter));
    _buf.push_back(static_cast<uint8_t>(interlace));
    return _buf;
}

Chunk Chunk::parse(const uint8_t* buf, size_t len, size_t& offset) {
    Chunk result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.length, buf + offset, 4);
    result.length = swap32(result.length);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.type, buf + offset, 4);
    offset += 4;
    if (offset + result.length > len) throw std::runtime_error("buffer overflow");
    result.data.assign(buf + offset, buf + offset + result.length);
    offset += result.length;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.crc, buf + offset, 4);
    result.crc = swap32(result.crc);
    offset += 4;
    return result;
}

std::string Chunk::to_json() const {
    std::string s = "{";
    s += "\"length\":";
    s += std::to_string(length);
    s += ",";
    s += "\"type\":";
    s += "[";
    for (size_t i = 0; i < 4; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(type[i]);
    }
    s += "]";
    s += ",";
    s += "\"data\":";
    s += "[";
    for (size_t i = 0; i < data.size(); ++i) {
        if (i > 0) s += ",";
        s += std::to_string(data[i]);
    }
    s += "]";
    s += ",";
    s += "\"crc\":";
    s += std::to_string(crc);
    s += "}";
    return s;
}

std::vector<uint8_t> Chunk::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = swap32(static_cast<uint32_t>(data.size()));
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.insert(_buf.end(), type, type + 4);
    _buf.insert(_buf.end(), data.begin(), data.end());
    {
        uint32_t _tmp = swap32(crc);
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    return _buf;
}

PngFile PngFile::parse(const uint8_t* buf, size_t len, size_t& offset) {
    PngFile result;
    result.header = Header::parse(buf, len, offset);
    while (offset < len) {
        result.chunks.push_back(Chunk::parse(buf, len, offset));
    }
    return result;
}

std::string PngFile::to_json() const {
    std::string s = "{";
    s += "\"header\":";
    s += header.to_json();
    s += ",";
    s += "\"chunks\":";
    s += "[";
    for (size_t i = 0; i < chunks.size(); ++i) {
        if (i > 0) s += ",";
        s += chunks[i].to_json();
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> PngFile::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        auto _tmp = header.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    for (const auto& _item : chunks) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    return _buf;
}

} // namespace png
