// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
#include <stdexcept>

namespace png {

enum class ColorType : uint8_t {
    Grayscale = 0,
    RGB = 2,
    Palette = 3,
    GrayscaleAlpha = 4,
    RGBA = 6,
};

struct Header {
    uint8_t signature[8];

    static Header parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct IHDRData {
    uint32_t width;
    uint32_t height;
    uint8_t bit_depth;
    ColorType color_type;
    uint8_t compression;
    uint8_t filter;
    uint8_t interlace;

    static IHDRData parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct Chunk {
    uint32_t length;
    uint8_t type[4];
    std::vector<uint8_t> data;
    uint32_t crc;

    static Chunk parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct PngFile {
    Header header;
    std::vector<Chunk> chunks;

    static PngFile parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

} // namespace png
