"""Generated by cleave. Do not edit."""

from __future__ import annotations

import enum
import json
import struct
from dataclasses import dataclass


class ColorType(enum.IntEnum):
    Grayscale = 0
    RGB = 2
    Palette = 3
    GrayscaleAlpha = 4
    RGBA = 6


@dataclass
class Header:
    signature: bytes

    @classmethod
    def parse(cls, buf: bytes, offset: int = 0) -> tuple["Header", int]:
        signature = buf[offset:offset + 8]
        offset += 8
        return cls(
            signature=signature,
        ), offset

    def to_json(self) -> str:
        return json.dumps(self._to_dict())

    def _to_dict(self) -> dict:
        d = {}
        d["signature"] = list(self.signature)
        return d

    def to_bytes(self) -> bytes:
        _buf = bytearray()
        _buf += self.signature
        return bytes(_buf)


@dataclass
class IHDRData:
    width: int
    height: int
    bit_depth: int
    color_type: "ColorType"
    compression: int
    filter: int
    interlace: int

    @classmethod
    def parse(cls, buf: bytes, offset: int = 0) -> tuple["IHDRData", int]:
        width = struct.unpack_from(">I", buf, offset)[0]
        offset += 4
        height = struct.unpack_from(">I", buf, offset)[0]
        offset += 4
        bit_depth = struct.unpack_from(">B", buf, offset)[0]
        offset += 1
        color_type = ColorType(struct.unpack_from(">B", buf, offset)[0])
        offset += 1
        compression = struct.unpack_from(">B", buf, offset)[0]
        offset += 1
        filter = struct.unpack_from(">B", buf, offset)[0]
        offset += 1
        interlace = struct.unpack_from(">B", buf, offset)[0]
        offset += 1
        return cls(
            width=width,
            height=height,
            bit_depth=bit_depth,
            color_type=color_type,
            compression=compression,
            filter=filter,
            interlace=interlace,
        ), offset

    def to_json(self) -> str:
        return json.dumps(self._to_dict())

    def _to_dict(self) -> dict:
        d = {}
        d["width"] = self.width
        d["height"] = self.height
        d["bit_depth"] = self.bit_depth
        d["color_type"] = self.color_type.name
        d["compression"] = self.compression
        d["filter"] = self.filter
        d["interlace"] = self.interlace
        return d

    def to_bytes(self) -> bytes:
        _buf = bytearray()
        _buf += struct.pack(">I", self.width)
        _buf += struct.pack(">I", self.height)
        _buf += struct.pack(">B", self.bit_depth)
        _buf += struct.pack(">B", int(self.color_type))
        _buf += struct.pack(">B", self.compression)
        _buf += struct.pack(">B", self.filter)
        _buf += struct.pack(">B", self.interlace)
        return bytes(_buf)


@dataclass
class Chunk:
    length: int
    type: bytes
    data: bytes
    crc: int

    @classmethod
    def parse(cls, buf: bytes, offset: int = 0) -> tuple["Chunk", int]:
        length = struct.unpack_from(">I", buf, offset)[0]
        offset += 4
        type = buf[offset:offset + 4]
        offset += 4
        data = buf[offset:offset + length]
        offset += length
        crc = struct.unpack_from(">I", buf, offset)[0]
        offset += 4
        return cls(
            length=length,
            type=type,
            data=data,
            crc=crc,
        ), offset

    def to_json(self) -> str:
        return json.dumps(self._to_dict())

    def _to_dict(self) -> dict:
        d = {}
        d["length"] = self.length
        d["type"] = list(self.type)
        d["data"] = list(self.data)
        d["crc"] = self.crc
        return d

    def to_bytes(self) -> bytes:
        _buf = bytearray()
        _buf += struct.pack(">I", len(self.data))
        _buf += self.type
        _buf += self.data
        _buf += struct.pack(">I", self.crc)
        return bytes(_buf)


@dataclass
class PngFile:
    header: "Header"
    chunks: list["Chunk"]

    @classmethod
    def parse(cls, buf: bytes, offset: int = 0) -> tuple["PngFile", int]:
        header, offset = Header.parse(buf, offset)
        chunks = []
        while offset < len(buf):
            _item, offset = Chunk.parse(buf, offset)
            chunks.append(_item)
        return cls(
            header=header,
            chunks=chunks,
        ), offset

    def to_json(self) -> str:
        return json.dumps(self._to_dict())

    def _to_dict(self) -> dict:
        d = {}
        d["header"] = self.header._to_dict()
        d["chunks"] = [item._to_dict() for item in self.chunks]
        return d

    def to_bytes(self) -> bytes:
        _buf = bytearray()
        _buf += self.header.to_bytes()
        for _item in self.chunks:
            _buf += _item.to_bytes()
        return bytes(_buf)

