// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
#include <stdexcept>
#include <optional>

namespace validation {

struct Header {
    uint32_t magic;
    uint16_t version;
    uint8_t flags;

    static Header parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct Record {
    std::string name;
    uint8_t priority;
    uint8_t has_data;
    std::optional<uint32_t> data;

    static Record parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct Container {
    Header header;
    uint32_t record_count;
    std::vector<Record> records;

    static Container parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

} // namespace validation
