"""Generated by cleave. Do not edit."""

from __future__ import annotations

import enum
import json
import struct
from dataclasses import dataclass
from typing import Optional


@dataclass
class Header:
    magic: int
    version: int
    flags: int

    @classmethod
    def parse(cls, buf: bytes, offset: int = 0) -> tuple["Header", int]:
        magic = struct.unpack_from(">I", buf, offset)[0]
        offset += 4
        if not (magic == 1129070934):
            raise ValueError("invalid magic number")
        version = struct.unpack_from(">H", buf, offset)[0]
        offset += 2
        if not (version >= 1):
            raise ValueError("version must be at least 1")
        if not (version <= 100):
            raise ValueError("version must be at most 100")
        flags = struct.unpack_from(">B", buf, offset)[0]
        offset += 1
        if not ((flags >= 0) and (flags <= 7)):
            raise ValueError("flags must be between 0 and 7")
        return cls(
            magic=magic,
            version=version,
            flags=flags,
        ), offset

    def to_json(self) -> str:
        return json.dumps(self._to_dict())

    def _to_dict(self) -> dict:
        d = {}
        d["magic"] = self.magic
        d["version"] = self.version
        d["flags"] = self.flags
        return d

    def to_bytes(self) -> bytes:
        _buf = bytearray()
        _buf += struct.pack(">I", self.magic)
        _buf += struct.pack(">H", self.version)
        _buf += struct.pack(">B", self.flags)
        return bytes(_buf)


@dataclass
class Record:
    name: str
    priority: int
    has_data: int
    data: Optional[int]

    @classmethod
    def parse(cls, buf: bytes, offset: int = 0) -> tuple["Record", int]:
        _raw = buf[offset:offset + 64]
        offset += 64
        _end = _raw.find(0)
        name = _raw[:_end].decode("utf-8") if _end >= 0 else _raw.decode("utf-8")
        priority = struct.unpack_from("<B", buf, offset)[0]
        offset += 1
        if not ((priority >= 1) and (priority <= 3)):
            raise ValueError("priority must be low (1), medium (2), or high (3)")
        has_data = struct.unpack_from("<B", buf, offset)[0]
        offset += 1
        if (has_data != 0):
            data = struct.unpack_from("<I", buf, offset)[0]
            offset += 4
        else:
            data = None
        return cls(
            name=name,
            priority=priority,
            has_data=has_data,
            data=data,
        ), offset

    def to_json(self) -> str:
        return json.dumps(self._to_dict())

    def _to_dict(self) -> dict:
        d = {}
        d["name"] = self.name
        d["priority"] = self.priority
        d["has_data"] = self.has_data
        if self.data is not None:
            d["data"] = self.data
        else:
            d["data"] = None
        return d

    def to_bytes(self) -> bytes:
        _buf = bytearray()
        _raw = self.name.encode("utf-8")
        _buf += _raw + bytes([0]) * (64 - len(_raw))
        _buf += struct.pack("<B", self.priority)
        _buf += struct.pack("<B", self.has_data)
        if self.data is not None:
            _buf += struct.pack("<I", self.data)
        return bytes(_buf)


@dataclass
class Container:
    header: "Header"
    record_count: int
    records: list["Record"]

    @classmethod
    def parse(cls, buf: bytes, offset: int = 0) -> tuple["Container", int]:
        header, offset = Header.parse(buf, offset)
        record_count = struct.unpack_from(">I", buf, offset)[0]
        offset += 4
        records = []
        for _ in range(header.record_count):
            _item, offset = Record.parse(buf, offset)
            records.append(_item)
        return cls(
            header=header,
            record_count=record_count,
            records=records,
        ), offset

    def to_json(self) -> str:
        return json.dumps(self._to_dict())

    def _to_dict(self) -> dict:
        d = {}
        d["header"] = self.header._to_dict()
        d["record_count"] = self.record_count
        d["records"] = [item._to_dict() for item in self.records]
        return d

    def to_bytes(self) -> bytes:
        _buf = bytearray()
        _buf += self.header.to_bytes()
        _buf += struct.pack(">I", self.record_count)
        for _item in self.records:
            _buf += _item.to_bytes()
        return bytes(_buf)

