// Generated by cleave. Do not edit.
#include "validation.h"

namespace validation {

namespace {

template <typename T>
T swap16(T val) {
    uint16_t v;
    std::memcpy(&v, &val, sizeof(v));
    v = (v >> 8) | (v << 8);
    T out;
    std::memcpy(&out, &v, sizeof(out));
    return out;
}

template <typename T>
T swap32(T val) {
    uint32_t v;
    std::memcpy(&v, &val, sizeof(v));
    v = ((v >> 24) & 0xFF) | ((v >> 8) & 0xFF00) | ((v << 8) & 0xFF0000) | ((v << 24) & 0xFF000000);
    T out;
    std::memcpy(&out, &v, sizeof(out));
    return out;
}

} // namespace

Header Header::parse(const uint8_t* buf, size_t len, size_t& offset) {
    Header result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.magic, buf + offset, 4);
    result.magic = swap32(result.magic);
    offset += 4;
    if (!((result.magic == 1129070934))) {
        throw std::runtime_error("invalid magic number");
    }
    if (offset + 2 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.version, buf + offset, 2);
    result.version = swap16(result.version);
    offset += 2;
    if (!((result.version >= 1))) {
        throw std::runtime_error("version must be at least 1");
    }
    if (!((result.version <= 100))) {
        throw std::runtime_error("version must be at most 100");
    }
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.flags = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (!(((result.flags >= 0) && (result.flags <= 7)))) {
        throw std::runtime_error("flags must be between 0 and 7");
    }
    return result;
}

std::string Header::to_json() const {
    std::string s = "{";
    s += "\"magic\":";
    s += std::to_string(magic);
    s += ",";
    s += "\"version\":";
    s += std::to_string(version);
    s += ",";
    s += "\"flags\":";
    s += std::to_string(flags);
    s += "}";
    return s;
}

std::vector<uint8_t> Header::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = swap32(magic);
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint16_t _tmp = swap16(version);
        uint8_t _raw[2];
        std::memcpy(_raw, &_tmp, 2);
        _buf.insert(_buf.end(), _raw, _raw + 2);
    }
    _buf.push_back(static_cast<uint8_t>(flags));
    return _buf;
}

Record Record::parse(const uint8_t* buf, size_t len, size_t& offset) {
    Record result;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    {
        size_t _n = strnlen(reinterpret_cast<const char*>(buf + offset), 64);
        result.name.assign(reinterpret_cast<const char*>(buf + offset), _n);
        offset += 64;
    }
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.priority = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (!(((result.priority >= 1) && (result.priority <= 3)))) {
        throw std::runtime_error("priority must be low (1), medium (2), or high (3)");
    }
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.has_data = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if ((result.has_data != 0)) {
        if (offset + 4 > len) throw std::runtime_error("buffer overflow");
        std::memcpy(&result.data, buf + offset, 4);
        offset += 4;
    }
    return result;
}

std::string Record::to_json() const {
    std::string s = "{";
    s += "\"name\":";
    s += "\"" + name + "\"";
    s += ",";
    s += "\"priority\":";
    s += std::to_string(priority);
    s += ",";
    s += "\"has_data\":";
    s += std::to_string(has_data);
    s += ",";
    s += "\"data\":";
    if (data.has_value()) {
        s += std::to_string(data.value());
    } else {
        s += "null";
    }
    s += "}";
    return s;
}

std::vector<uint8_t> Record::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        std::vector<uint8_t> _tmp(64, 0);
        std::memcpy(_tmp.data(), name.data(), std::min(name.size(), static_cast<size_t>(64)));
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    _buf.push_back(static_cast<uint8_t>(priority));
    _buf.push_back(static_cast<uint8_t>(has_data));
    if (data.has_value()) {
        {
            uint32_t _tmp = data;
            uint8_t _raw[4];
            std::memcpy(_raw, &_tmp, 4);
            _buf.insert(_buf.end(), _raw, _raw + 4);
        }
    }
    return _buf;
}

Container Container::parse(const uint8_t* buf, size_t len, size_t& offset) {
    Container result;
    result.header = Header::parse(buf, len, offset);
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.record_count, buf + offset, 4);
    result.record_count = swap32(result.record_count);
    offset += 4;
    for (size_t i = 0; i < result.header.record_count; ++i) {
        result.records.push_back(Record::parse(buf, len, offset));
    }
    return result;
}

std::string Container::to_json() const {
    std::string s = "{";
    s += "\"header\":";
    s += header.to_json();
    s += ",";
    s += "\"record_count\":";
    s += std::to_string(record_count);
    s += ",";
    s += "\"records\":";
    s += "[";
    for (size_t i = 0; i < records.size(); ++i) {
        if (i > 0) s += ",";
        s += records[i].to_json();
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> Container::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        auto _tmp = header.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    {
        uint32_t _tmp = swap32(record_count);
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : records) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    return _buf;
}

} // namespace validation
